# Prepare long strips that have already been processed, for viewer tool

In [4]:
#%% imports
from pathlib import Path
# import json
# import configparser
import pprint
pp = pprint.PrettyPrinter(indent=4);
import time
import math
from collections import namedtuple

# # pip install slicerio
# import slicerio.server

# # packages for 3d
# #   # for OCT 3D stuff and using in jupyter
# #   - trame-jupyter-extension
# #   - trame
# #   - trame-vtk
# #   - trame-vuetify
# #   - ipywidgets

import matplotlib.pyplot as plt
import plotly.express as px

# interactive panels
import panel as pn
pn.extension('plotly');

import numpy as np
import pandas as pd
import addict

import cv2
import skimage
import scipy.signal
import networkx as nx

import pyvista as pv
from PIL import Image
import SimpleITK as sitk

# with vedo
#from vedo import dataurl, Volume, Text2D
import vedo
vedo.settings.default_backend = 'vtk'
#from vedo.applications import Slicer3DPlotter
import naatos_oct_tools.plotters.vedo_plotters as vedo_plotters
import naatos_oct_tools.plotters.sitk_plotters as sitk_plotters

import naatos_oct_tools.thorlabs_oct_file_reading
import naatos_oct_tools.oct_linear_scan_processing

In [5]:
# Magics to autoreload submodules when they are modified
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
#%% Test Record Excel
dftests = pd.read_excel(
    r'C:\Users\SimonGhionea\Global Health Labs, Inc\NAATOS Product Feasibility - TB V1 - General - Internal - Wax Valve\OCT\Test\OCT_wax_valve_test_record.xlsx',
    skiprows=1
)
dftests = dftests.iloc[:,1:]
dftests.rename(columns={'Unnamed: 19':'Notes'},inplace=True)
dftests

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Notes
0,NaN,2025-03-26,GHL_pyapp_20250326T1258,oven aging test day 1,strip 7,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025-03-26,GHL_pyapp_20250326T1403,oven aging test day 1,strip 10,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2025-03-26,GHL_pyapp_20250326T1416,oven aging test day 1,strip 14,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2025-03-27,GHL_pyapp_20250327T1428,oven aging test day 2,strip 7,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2025-03-27,GHL_pyapp_20250327T1438,oven aging test day 2,strip 10,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,212.0,2025-07-25,GHL_OldStriper_20250725T1509,722Valves0.325to0.4,RG_7-22_12,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN
218,213.0,2025-07-25,GHL_OldStriper_20250725T1514,722Valves0.325to0.4,RG_7-22_18,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN
219,214.0,2025-07-25,GHL_OldStriper_20250725T1528,722Valves0.325to0.4,RG_7-22_10,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN
220,215.0,2025-07-25,GHL_OldStriper_20250725T1532,722Valves0.325to0.4,RG_7-22_9,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN
221,216.0,2025-07-25,GHL_OldStriper_20250725T1519,722Valves0.325to0.4,RG_7-22_6,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN

In [7]:
#%% Filter The Tests To View
# dfmasks = [
#     (dftests['Test date']<'2025-03-28') & (dftests['Test date']>='2025-03-26'),
#     dftests['Test name'] != 'GHL_pyapp_20250326T1258'
# ]
# dfmasks = [
#     (dftests['Test date']<='2025-04-15') & (dftests['Test date']>='2025-04-14')
# ]
# dfmasks = [
#     (dftests['Test date']=='2025-05-05')
# ]
dfmasks = [
    #dftests['Test date']=='2025-06-05',
    #(dftests['Test date']=='2025-06-11') | (dftests['Test date']=='2025-06-12'),
    #(dftests['Test date']=='2025-06-05') | (dftests['Test date']=='2025-06-11') | (dftests['Test date']=='2025-06-12'),
    #(dftests['Test date']>='2025-06-05') & (dftests['Test date']<'2025-07-25')
    (dftests['Test date']>='2025-06-05')
    #dftests['Test name']!='GHL_pyapp_20250512T',
    #dftests['ProcessingNotes'].str.startswith('done,2'),
    #~dftests['Batch'].str.contains('Valve')
]

dffilt = dftests[np.all(dfmasks,axis=0)]
dffilt

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Notes
74,69.0,2025-06-05,GHL_pyapp_20250605T1211,Jun5 0.325-0.349mg/mm bag ylw,BluePenES0323#16 0.335,0.335,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2,processing decent",redo fail2
75,70.0,2025-06-05,GHL_pyapp_20250605T1214,Jun5 0.325-0.349mg/mm bag ylw,ES0403#8 0.326,0.326,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1,processing decent",redo fail2
76,71.0,2025-06-05,GHL_pyapp_20250605T1218,Jun5 0.325-0.349mg/mm bag ylw,ES0402#11 0.342,0.342,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1,bad results processing",NaN
77,72.0,2025-06-05,GHL_pyapp_20250605T1225,Jun5 0.325-0.349mg/mm bag ylw,ES0403#6 0.331,0.331,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1,processing decent",NaN
78,73.0,2025-06-05,GHL_pyapp_20250605T1228,Jun5 0.325-0.349mg/mm bag ylw,ES0403#19 0.329,0.329,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1,processing decent",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,212.0,2025-07-25,GHL_OldStriper_20250725T1509,722Valves0.325to0.4,RG_7-22_12,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN
218,213.0,2025-07-25,GHL_OldStriper_20250725T1514,722Valves0.325to0.4,RG_7-22_18,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN
219,214.0,2025-07-25,GHL_OldStriper_20250725T1528,722Valves0.325to0.4,RG_7-22_10,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN
220,215.0,2025-07-25,GHL_OldStriper_20250725T1532,722Valves0.325to0.4,RG_7-22_9,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN
221,216.0,2025-07-25,GHL_OldStriper_20250725T1519,722Valves0.325to0.4,RG_7-22_6,NaN,Vacuum,9.0,3.5,1.998125,...,297.3,132.5,164.8,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.18,3.45,"done 7/25, 10.6 hours for 38 strips",NaN

In [8]:
#%% Load OCT study information
folder_octexport_root = Path(r'\\file.corp.ghlabs.org\Shared\Projects\NAATOS\V1\NAATOS_OCT_WORK\OCTExport')
#folder_octexport_root = Path(r'D:\SGProjects\NAATOS\OCTlocal')

folder_temp = Path(r'D:\TEMP')

In [9]:
# Instantiate OCT_Study_Folder objects for each 
octstudies = [];
for idx,record in dffilt.iterrows():
    octstudy = naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder(record['Test name'],folder_octexport_root);
    octstudies.append(octstudy);

STUDY: GHL_pyapp_20250605T1211
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1214
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1218
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1225
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1228
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1233
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1301
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1326
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1330
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1333
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1336
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1340
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1344
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1347
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1350
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1402
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1407
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1410
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1414
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1417
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1422
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1425
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1428
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1431
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1437
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1440
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1443
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1447
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1450
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1454
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1457
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1522
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1528
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1532
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1536
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1539
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1542
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1546
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1557
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1600
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1605
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1611
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1615
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1618
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1621
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1625
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1628
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1633
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1636
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1645
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1649
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1656
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1704
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1709
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1715
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1718
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1722
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1728
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1731
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1734
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250611T1738
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0724
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0727
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0731
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0734
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0748
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0752
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0755
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0759
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0804
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250612T0807
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_WaxRobot_20250711T1438
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 22,
    'study_num_vtk_files': 0}
STUDY: GHL_WaxRobot_20250711T1442
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 22,
    'study_num_vtk_files': 0}
STUDY: GHL_WaxRobot_20250711T1501
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 29,
    'study_num_vtk_files': 0}
STUDY: GHL_WaxRobot_20250711T1513
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 30,
    'study_num_vtk_files': 0}
STUDY: GHL_WaxRobot_20250711T1519
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 30,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1202
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1206
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1213
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1216
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1220
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1223
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1226
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1229
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1232
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1235
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1239
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_OldStriper_20250722T1243
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,

# Parse Through The OCTSTUDIES

In [10]:
#%% Load OCTSTUDY object, and read it's summary / results data
octstudies_to_run = [];
for idx,octstudy in enumerate(octstudies):
    octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder;
    print('~~~~~~~');
    print(octstudy.name);
    pp.pprint(octstudy.resultsCheck())
    doWeRunTheNotebook = any([v is False for k,v in octstudy.resultsCheck().items()])
    print('Run?',doWeRunTheNotebook)
    if(not doWeRunTheNotebook):
        octstudies_to_run.append(octstudy);

print('~~~~~~~');
print('We will analyze data for {:} octstudies.'.format(len(octstudies_to_run)))
print([x.name for x in octstudies_to_run]);

~~~~~~~
GHL_pyapp_20250605T1211
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1214
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1218
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1225
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1228
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1233
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1301
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1326
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1330
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1333
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1336
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1340
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1344
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1347
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1350
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1402
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1407
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1410
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1414
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1417
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1422
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1425
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1428
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1431
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1437
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1440
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1443
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1447
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1450
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1454
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1457
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1522
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1528
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1532
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1536
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1539
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1542
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1546
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1557
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1600
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1605
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1611
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1615
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1618
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1621
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1625
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1628
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1633
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250605T1636
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1645
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1649
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1656
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1704
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1709
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1715
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1718
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1722
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1728
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1731
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1734
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250611T1738
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0724
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0727
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0731
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0734
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0748
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0752
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0755
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0759
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0804
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_pyapp_20250612T0807
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_WaxRobot_20250711T1438
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_WaxRobot_20250711T1442
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_WaxRobot_20250711T1501
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_WaxRobot_20250711T1513
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_WaxRobot_20250711T1519
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1202
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1206
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1213
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1216
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1220
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1223
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1226
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1229
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1232
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1235
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1239
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1243
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1254
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1257
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1300
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1303
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1306
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1309
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1312
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1318
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1339
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1342
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1348
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1351
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1354
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1357
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1400
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1403
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1406
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1409
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1413
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1418
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250722T1421
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1022
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1027
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1030
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1034
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1037
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1041
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1045
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1049
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1052
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1056
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1100
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1159
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1335
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1339
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1342
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1345
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1348
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1352
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~
GHL_OldStriper_20250725T1355
{   'along_strip_data_extracted': ['/dfstepA'],
    'exist_data_extracted': True,
    'figoutmp4_stepA': True}
Run? False
~~~~~~~

# 1. Load all Data

In [11]:
#octstudies_to_run = [octstudies_to_run[0]]
dfs = [];
for idx,octstudy in enumerate(octstudies_to_run):
    print(octstudy.name)

    #octstudy.load_previously_saved_merged_volume();

    data_extracted = octstudy.load_data_extracted();
    dfstep = octstudy.load_data_extracted_along_strip();
    
    dfstep['octstudy'] = octstudy;

    dfs.append(dfstep)
dfsteps = pd.concat(dfs,keys=[x.name for x in octstudies_to_run]);
del dfs;

GHL_pyapp_20250605T1211
Loading /dfstepA
GHL_pyapp_20250605T1214
Loading /dfstepA
GHL_pyapp_20250605T1218
Loading /dfstepA
GHL_pyapp_20250605T1225
Loading /dfstepA
GHL_pyapp_20250605T1228
Loading /dfstepA
GHL_pyapp_20250605T1233
Loading /dfstepA
GHL_pyapp_20250605T1301
Loading /dfstepA
GHL_pyapp_20250605T1326
Loading /dfstepA
GHL_pyapp_20250605T1330
Loading /dfstepA
GHL_pyapp_20250605T1333
Loading /dfstepA
GHL_pyapp_20250605T1336
Loading /dfstepA
GHL_pyapp_20250605T1340
Loading /dfstepA
GHL_pyapp_20250605T1344
Loading /dfstepA
GHL_pyapp_20250605T1347
Loading /dfstepA
GHL_pyapp_20250605T1350
Loading /dfstepA
GHL_pyapp_20250605T1402
Loading /dfstepA
GHL_pyapp_20250605T1407
Loading /dfstepA
GHL_pyapp_20250605T1410
Loading /dfstepA
GHL_pyapp_20250605T1414
Loading /dfstepA
GHL_pyapp_20250605T1417
Loading /dfstepA
GHL_pyapp_20250605T1422
Loading /dfstepA
GHL_pyapp_20250605T1425
Loading /dfstepA
GHL_pyapp_20250605T1428
Loading /dfstepA
GHL_pyapp_20250605T1431
Loading /dfstepA
GHL_pyapp_20250605T1437
Loading /dfstepA
GHL_pyapp_20250605T1440
Loading /dfstepA
GHL_pyapp_20250605T1443
Loading /dfstepA
GHL_pyapp_20250605T1447
Loading /dfstepA
GHL_pyapp_20250605T1450
Loading /dfstepA
GHL_pyapp_20250605T1454
Loading /dfstepA
GHL_pyapp_20250605T1457
Loading /dfstepA
GHL_pyapp_20250605T1522
Loading /dfstepA
GHL_pyapp_20250605T1528
Loading /dfstepA
GHL_pyapp_20250605T1532
Loading /dfstepA
GHL_pyapp_20250605T1536
Loading /dfstepA
GHL_pyapp_20250605T1539
Loading /dfstepA
GHL_pyapp_20250605T1542
Loading /dfstepA
GHL_pyapp_20250605T1546
Loading /dfstepA
GHL_pyapp_20250605T1557
Loading /dfstepA
GHL_pyapp_20250605T1600
Loading /dfstepA
GHL_pyapp_20250605T1605
Loading /dfstepA
GHL_pyapp_20250605T1611
Loading /dfstepA
GHL_pyapp_20250605T1615
Loading /dfstepA
GHL_pyapp_20250605T1618
Loading /dfstepA
GHL_pyapp_20250605T1621
Loading /dfstepA
GHL_pyapp_20250605T1625
Loading /dfstepA
GHL_pyapp_20250605T1628
Loading /dfstepA
GHL_pyapp_20250605T1633
Loading /dfstepA
GHL_pyapp_20250605T1636
Loading /dfstepA
GHL_pyapp_20250611T1645
Loading /dfstepA
GHL_pyapp_20250611T1649
Loading /dfstepA
GHL_pyapp_20250611T1656
Loading /dfstepA
GHL_pyapp_20250611T1704
Loading /dfstepA
GHL_pyapp_20250611T1709
Loading /dfstepA
GHL_pyapp_20250611T1715
Loading /dfstepA
GHL_pyapp_20250611T1718
Loading /dfstepA
GHL_pyapp_20250611T1722
Loading /dfstepA
GHL_pyapp_20250611T1728
Loading /dfstepA
GHL_pyapp_20250611T1731
Loading /dfstepA
GHL_pyapp_20250611T1734
Loading /dfstepA
GHL_pyapp_20250611T1738
Loading /dfstepA
GHL_pyapp_20250612T0724
Loading /dfstepA
GHL_pyapp_20250612T0727
Loading /dfstepA
GHL_pyapp_20250612T0731
Loading /dfstepA
GHL_pyapp_20250612T0734
Loading /dfstepA
GHL_pyapp_20250612T0748
Loading /dfstepA
GHL_pyapp_20250612T0752
Loading /dfstepA
GHL_pyapp_20250612T0755
Loading /dfstepA
GHL_pyapp_20250612T0759
Loading /dfstepA
GHL_pyapp_20250612T0804
Loading /dfstepA
GHL_pyapp_20250612T0807
Loading /dfstepA
GHL_WaxRobot_20250711T1438
Loading /dfstepA
GHL_WaxRobot_20250711T1442
Loading /dfstepA
GHL_WaxRobot_20250711T1501
Loading /dfstepA
GHL_WaxRobot_20250711T1513
Loading /dfstepA
GHL_WaxRobot_20250711T1519
Loading /dfstepA
GHL_OldStriper_20250722T1202
Loading /dfstepA
GHL_OldStriper_20250722T1206
Loading /dfstepA
GHL_OldStriper_20250722T1213
Loading /dfstepA
GHL_OldStriper_20250722T1216
Loading /dfstepA
GHL_OldStriper_20250722T1220
Loading /dfstepA
GHL_OldStriper_20250722T1223
Loading /dfstepA
GHL_OldStriper_20250722T1226
Loading /dfstepA
GHL_OldStriper_20250722T1229
Loading /dfstepA
GHL_OldStriper_20250722T1232
Loading /dfstepA
GHL_OldStriper_20250722T1235
Loading /dfstepA
GHL_OldStriper_20250722T1239
Loading /dfstepA
GHL_OldStriper_20250722T1243
Loading /dfstepA
GHL_OldStriper_20250722T1254
Loading /dfstepA
GHL_OldStriper_20250722T1257
Loading /dfstepA
GHL_OldStriper_20250722T1300
Loading /dfstepA
GHL_OldStriper_20250722T1303
Loading /dfstepA
GHL_OldStriper_20250722T1306
Loading /dfstepA
GHL_OldStriper_20250722T1309
Loading /dfstepA
GHL_OldStriper_20250722T1312
Loading /dfstepA
GHL_OldStriper_20250722T1318
Loading /dfstepA
GHL_OldStriper_20250722T1339
Loading /dfstepA
GHL_OldStriper_20250722T1342
Loading /dfstepA
GHL_OldStriper_20250722T1348
Loading /dfstepA
GHL_OldStriper_20250722T1351
Loading /dfstepA
GHL_OldStriper_20250722T1354
Loading /dfstepA
GHL_OldStriper_20250722T1357
Loading /dfstepA
GHL_OldStriper_20250722T1400
Loading /dfstepA
GHL_OldStriper_20250722T1403
Loading /dfstepA
GHL_OldStriper_20250722T1406
Loading /dfstepA
GHL_OldStriper_20250722T1409
Loading /dfstepA
GHL_OldStriper_20250722T1413
Loading /dfstepA
GHL_OldStriper_20250722T1418
Loading /dfstepA
GHL_OldStriper_20250722T1421
Loading /dfstepA
GHL_OldStriper_20250725T1022
Loading /dfstepA
GHL_OldStriper_20250725T1027
Loading /dfstepA
GHL_OldStriper_20250725T1030
Loading /dfstepA
GHL_OldStriper_20250725T1034
Loading /dfstepA
GHL_OldStriper_20250725T1037
Loading /dfstepA
GHL_OldStriper_20250725T1041
Loading /dfstepA
GHL_OldStriper_20250725T1045
Loading /dfstepA
GHL_OldStriper_20250725T1049
Loading /dfstepA
GHL_OldStriper_20250725T1052
Loading /dfstepA
GHL_OldStriper_20250725T1056
Loading /dfstepA
GHL_OldStriper_20250725T1100
Loading /dfstepA
GHL_OldStriper_20250725T1159
Loading /dfstepA
GHL_OldStriper_20250725T1335
Loading /dfstepA
GHL_OldStriper_20250725T1339
Loading /dfstepA
GHL_OldStriper_20250725T1342
Loading /dfstepA
GHL_OldStriper_20250725T1345
Loading /dfstepA
GHL_OldStriper_20250725T1348
Loading /dfstepA
GHL_OldStriper_20250725T1352
Loading /dfstepA
GHL_OldStriper_20250725T1355
Loading /dfstepA
GHL_OldStriper_20250725T1358
Loading /dfstepA
GHL_OldStriper_20250725T1401
Loading /dfstepA
GHL_OldStriper_20250725T1406
Loading /dfstepA
GHL_OldStriper_20250725T1409
Loading /dfstepA
GHL_OldStriper_20250725T1413
Loading /dfstepA
GHL_OldStriper_20250725T1417
Loading /dfstepA
GHL_OldStriper_20250725T1421
Loading /dfstepA
GHL_OldStriper_20250725T1425
Loading /dfstepA
GHL_OldStriper_20250725T1428
Loading /dfstepA
GHL_OldStriper_20250725T1431
Loading /dfstepA
GHL_OldStriper_20250725T1436
Loading /dfstepA
GHL_OldStriper_20250725T1439
Loading /dfstepA
GHL_OldStriper_20250725T1443
Loading /dfstepA
GHL_OldStriper_20250725T1457
Loading /dfstepA
GHL_OldStriper_20250725T1500
Loading /dfstepA
GHL_OldStriper_20250725T1509
Loading /dfstepA
GHL_OldStriper_20250725T1514
Loading /dfstepA
GHL_OldStriper_20250725T1528
Loading /dfstepA
GHL_OldStriper_20250725T1532
Loading /dfstepA
GHL_OldStriper_20250725T1519
Loading /dfstepA

In [12]:
import gc
gc.collect()

0

In [13]:
dfsteps

                                    pixel_depth_strip_top_sum_threshold  \
                             slice
GHL_pyapp_20250605T1211      5                                    30.24
                             10                                   32.16
                             15                                   33.40
                             20                                   35.56
                             25                                   34.44
...                                                                 ...
GHL_OldStriper_20250725T1519 8010                                 53.16
                             8015                                 55.56
                             8020                                 57.64
                             8025                                 59.68
                             8030                                 60.40

                                    pixel_depth_strip_top  \
                             slice
GHL_pyapp_20250605T1211      5                        323
                             10                       322
                             15                       322
                             20                       322
                             25                       321
...                                                   ...
GHL_OldStriper_20250725T1519 8010                     203
                             8015                     204
                             8020                     204
                             8025                     205
                             8030                     205

                                    pixel_depth_strip_bot  \
                             slice
GHL_pyapp_20250605T1211      5                        369
                             10                       369
                             15                       370
                             20                       368
                             25                       370
...                                                   ...
GHL_OldStriper_20250725T1519 8010                     247
                             8015                     246
                             8020                     247
                             8025                     247
                             8030                     247

                                    pixel_depth_wax_center  \
                             slice
GHL_pyapp_20250605T1211      5                         357
                             10                        356
                             15                        349
                             20                        350
                             25                        368
...                                                    ...
GHL_OldStriper_20250725T1519 8010                      228
                             8015                      228
                             8020                      232
                             8025                      232
                             8030                      232

                                                     px_wax_transverse_edges  \
                             slice
GHL_pyapp_20250605T1211      5      (56.035470941883766, 115.66230215827338)
                             10         (54.3269592476489, 116.359941089838)
                             15     (49.520063191153234, 118.82182061579653)
                             20     (50.178378378378376, 119.19511904761904)
                             25      (42.08465608465608, 118.88260869565218)
...                                                                      ...
GHL_OldStriper_20250725T1519 8010    (57.36587966488957, 109.67462686567164)
                             8015    (58.76654163540885, 109.72371007371008)
                             8020    (59.17307110438729, 111.95305785123966)
                             8025    (58.44257703081232, 112.56561085972851)
                             8030   (58.755721393034825, 112.53462282398453)

                                   wax_top_seed_candidate_px  \
                             slice
GHL_pyapp_20250605T1211      5                     (302, 86)
                             10                    (320, 85)
                             15                    (328, 83)
                             20                    (326, 84)
                             25                    (330, 80)
...                                                      ...
GHL_OldStriper_20250725T1519 8010                  (218, 83)
                             8015                  (218, 83)
                             8020                  (213, 85)
                             8025                  (221, 85)
                             8030                  (222, 85)

                                    wax_roi_valve_bottom  num_paths  bbox-0  \
                             slice
GHL_pyapp_20250605T1211      5                       161        NaN     NaN
                             10                      212        NaN     NaN
                             15                      192        NaN     NaN
                             20                      198        NaN     NaN
                             25                      195        NaN     NaN
...                                                  ...        ...     ...
GHL_OldStriper_20250725T1519 8010                    162        NaN     NaN
                             8015                    146        NaN     NaN
                             8020                    162        NaN     NaN
                             8025                    145        NaN     NaN
                             8030                    144        NaN     NaN

                                    bbox-1  ...  seg_orientation  \
                             slice          ...
GHL_pyapp_20250605T1211      5         NaN  ...              NaN
                             10        NaN  ...              NaN
                             15        NaN  ...              NaN
                             20        NaN  ...              NaN
                             25        NaN  ...              NaN
...                                    ...  ...              ...
GHL_OldStriper_20250725T1519 8010      NaN  ...         1.336657
                             8015      NaN  ...         1.319944
                             8020      NaN  ...         1.348547
                             8025      NaN  ...         1.334981
                             8030      NaN  ...         1.269507

                                    seg_axis_major_length  \
                             slice
GHL_pyapp_20250605T1211      5                        NaN
                             10                       NaN
                             15                       NaN
                             20                       NaN
                             25                       NaN
...                                                   ...
GHL_OldStriper_20250725T1519 8010              138.828288
                             8015              138.382614
                             8020              147.192930
                             8025              143.563564
                             8030              130.980347

                                    seg_axis_minor_length  seg_area  \
                             slice
GHL_pyapp_20250605T1211      5                        NaN       NaN
                             10                       NaN       NaN
                             15                       NaN       NaN
                             20                       NaN       NaN
                             25                       NaN       NaN
...                                                   ...       ...
GHL_OldStriper_20250725T1519 8010               54.879311    5069.0
                             8015               49.301071    4264.0
                             8020               49.015142    3831.0
                             8025               55.128453    3400.0
                             8030               58.095583    2809.0

                                    seg_area_bbox  seg_area_convex  \
                             slice
GHL_pyapp_20250605T1211      5                NaN              NaN
                             10               NaN              NaN
                             15               NaN              NaN
                             20               NaN              NaN
                             25               NaN              NaN
...                                           ...              ...
GHL_OldStriper_20250725T1519 8010          9230.0           6512.0
                             8015          8190.0           5894.0
                             8020          8040.0           5878.0
                             8025          7482.0           5714.0
                             8030          7112.0           5208.0

                                    seg_area_filled  seg_euler_number  \
                             slice
GHL_pyapp_20250605T1211      5                  NaN               NaN
                             10                 NaN               NaN
                             15                 NaN               NaN
                             20                 NaN               NaN
                             25                 NaN               NaN
...                                             ...               ...
GHL_OldStriper_20250725T1519 8010            5435.0              -6.0
                             8015            4716.0              -6.0
                             8020            4055.0              -5.0
                             8025            3450.0               0.0
                             8030            2809.0               1.0

                                    seg_extent  seg_feret_diameter_max
                             slice
GHL_pyapp_20250605T1211      5             NaN                     NaN
                             10            NaN                     NaN
                             15            NaN                     NaN
                             20            NaN                     NaN
                             25            NaN                     NaN
...                                        ...                     ...
GHL_OldStriper_20250725T1519 8010     0.549187              148.081059
                             8015     0.520635              134.714513
                             8020     0.476493              136.062486
                             8025     0.454424              132.219514
                             8030     0.394966              129.634100

[246586 rows x 42 columns]

In [17]:
dffilt['Batch'].unique()

array(['Jun5 0.325-0.349mg/mm bag ylw',
       'Jun5 0.375-0.400mg/mm bag blu crossouts',
       'Jun11InSpecSmallZiploc', 'July11WaxrobotStrips',
       'July17n18Oldstriper', '722Valves0.325to0.4'], dtype=object)

## 2. Save

In [18]:
cols_ignore = ['testseg_otsu_thresholds','testseg_otsu_regions','seg_thresh_sauvola_cutoff','pksA','pksB','pksB2','wax_segmentation']

df = dfsteps[[x for x in dfsteps.columns.tolist() if x not in cols_ignore]]
#df.to_hdf(folder_temp/'oct_results_summary_2025_06_17_allbathces.hdf',key='table');
#df.to_hdf(folder_temp/'oct_results_summary_2025_07_03_allbatches.hdf',key='table');
df.to_hdf(folder_temp/'oct_results_summary_2025_07_25b_allbatches.hdf',key='table');

C:\Users\SimonGhionea\AppData\Local\Temp\ipykernel_143048\2241103483.py:6: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['px_wax_transverse_edges', 'wax_top_seed_candidate_px', 'octstudy'], dtype='object')]

  df.to_hdf(folder_temp/'oct_results_summary_2025_07_25b_allbatches.hdf',key='table');