# Process and View Results From Multiple Longstrips

In [1]:
#%% imports
from pathlib import Path
# import json
# import configparser
import pprint
pp = pprint.PrettyPrinter(indent=4);
import time
import math
from collections import namedtuple

# # pip install slicerio
# import slicerio.server

# # packages for 3d
# #   # for OCT 3D stuff and using in jupyter
# #   - trame-jupyter-extension
# #   - trame
# #   - trame-vtk
# #   - trame-vuetify
# #   - ipywidgets

import matplotlib.pyplot as plt
import plotly.express as px

# interactive panels
import panel as pn
pn.extension('plotly');

import numpy as np
import pandas as pd
import addict

import cv2
import skimage
import scipy.signal
import networkx as nx

import pyvista as pv
from PIL import Image
import SimpleITK as sitk

# with vedo
#from vedo import dataurl, Volume, Text2D
import vedo
vedo.settings.default_backend = 'vtk'
#from vedo.applications import Slicer3DPlotter
import naatos_oct_tools.plotters.vedo_plotters as vedo_plotters
import naatos_oct_tools.plotters.sitk_plotters as sitk_plotters

import naatos_oct_tools.thorlabs_oct_file_reading
import naatos_oct_tools.oct_linear_scan_processing

In [2]:
# Magics to autoreload submodules when they are modified
%load_ext autoreload
%autoreload 2

In [8]:
#%% Test Record Excel
dftests = pd.read_excel(
    r'C:\Users\SimonGhionea\Global Health Labs, Inc\NAATOS Product Feasibility - TB V1 - General - Internal - Wax Valve\OCT\Test\OCT_wax_valve_test_record.xlsx',
    skiprows=1
)
dftests = dftests.iloc[:,1:]
dftests.rename(columns={'Unnamed: 19':'Notes'},inplace=True)
dftests

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Notes
0,NaN,2025-03-26,GHL_pyapp_20250326T1258,oven aging test day 1,strip 7,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025-03-26,GHL_pyapp_20250326T1403,oven aging test day 1,strip 10,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2025-03-26,GHL_pyapp_20250326T1416,oven aging test day 1,strip 14,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2025-03-27,GHL_pyapp_20250327T1428,oven aging test day 2,strip 7,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2025-03-27,GHL_pyapp_20250327T1438,oven aging test day 2,strip 10,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,113.0,2025-06-05,GHL_pyapp_20250605T1621,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#4 0.392,0.392,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
119,114.0,2025-06-05,GHL_pyapp_20250605T1625,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#1BluMark 0.382,0.382,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
120,115.0,2025-06-05,GHL_pyapp_20250605T1628,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#7 0.383,0.383,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,3",NaN
121,116.0,2025-06-05,GHL_pyapp_20250605T1633,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#14 0.384,0.384,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
122,117.0,2025-06-05,GHL_pyapp_20250605T1636,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#26 0.398,0.398,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN

In [10]:
#%% Filter The Tests To View
# dfmasks = [
#     (dftests['Test date']<'2025-03-28') & (dftests['Test date']>='2025-03-26'),
#     dftests['Test name'] != 'GHL_pyapp_20250326T1258'
# ]
# dfmasks = [
#     (dftests['Test date']<='2025-04-15') & (dftests['Test date']>='2025-04-14')
# ]
# dfmasks = [
#     (dftests['Test date']=='2025-05-05')
# ]
dfmasks = [
    dftests['Test date']=='2025-06-05',
    #dftests['Test name']!='GHL_pyapp_20250512T',
    #dftests['ProcessingNotes'].str.startswith('done,2'),
    #~dftests['Batch'].str.contains('Valve')
]

dffilt = dftests[np.all(dfmasks,axis=0)]
dffilt

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Notes
74,69.0,2025-06-05,GHL_pyapp_20250605T1211,Jun5 0.325-0.349mg/mm bag ylw,BluePenES0323#16 0.335,0.335,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
75,70.0,2025-06-05,GHL_pyapp_20250605T1214,Jun5 0.325-0.349mg/mm bag ylw,ES0403#8 0.326,0.326,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
76,71.0,2025-06-05,GHL_pyapp_20250605T1218,Jun5 0.325-0.349mg/mm bag ylw,ES0402#11 0.342,0.342,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
77,72.0,2025-06-05,GHL_pyapp_20250605T1225,Jun5 0.325-0.349mg/mm bag ylw,ES0403#6 0.331,0.331,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
78,73.0,2025-06-05,GHL_pyapp_20250605T1228,Jun5 0.325-0.349mg/mm bag ylw,ES0403#19 0.329,0.329,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
79,74.0,2025-06-05,GHL_pyapp_20250605T1233,Jun5 0.325-0.349mg/mm bag ylw,ES0403#21 0.340,0.340,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
80,75.0,2025-06-05,GHL_pyapp_20250605T1301,Jun5 0.325-0.349mg/mm bag ylw,ES0403#30 0.345,0.345,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
81,76.0,2025-06-05,GHL_pyapp_20250605T1326,Jun5 0.325-0.349mg/mm bag ylw,ES0407#2 0.326,0.326,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
82,77.0,2025-06-05,GHL_pyapp_20250605T1330,Jun5 0.325-0.349mg/mm bag ylw,ES0331#31 0.334,0.334,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
83,78.0,2025-06-05,GHL_pyapp_20250605T1333,Jun5 0.325-0.349mg/mm bag ylw,ES0331#35 0.327,0.327,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,3",NaN
84,79.0,2025-06-05,GHL_pyapp_20250605T1336,Jun5 0.325-0.349mg/mm bag ylw,ES0401#4 0.325,0.325,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
85,80.0,2025-06-05,GHL_pyapp_20250605T1340,Jun5 0.325-0.349mg/mm bag ylw,ES0331#39 0.340,0.340,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
86,81.0,2025-06-05,GHL_pyapp_20250605T1344,Jun5 0.325-0.349mg/mm bag ylw,ES0331#49 0.348,0.348,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
87,82.0,2025-06-05,GHL_pyapp_20250605T1347,Jun5 0.325-0.349mg/mm bag ylw,ES0401#16 0.328,0.328,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
88,83.0,2025-06-05,GHL_pyapp_20250605T1350,Jun5 0.325-0.349mg/mm bag ylw,ES0401#17 0.328,0.328,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
89,84.0,2025-06-05,GHL_pyapp_20250605T1402,Jun5 0.325-0.349mg/mm bag ylw,ES0401#6 0.329,0.329,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
90,85.0,2025-06-05,GHL_pyapp_20250605T1407,Jun5 0.325-0.349mg/mm bag ylw,ES0328#21 0.334,0.334,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
91,86.0,2025-06-05,GHL_pyapp_20250605T1410,Jun5 0.325-0.349mg/mm bag ylw,0327#9 0.339,0.339,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
92,87.0,2025-06-05,GHL_pyapp_20250605T1414,Jun5 0.325-0.349mg/mm bag ylw,ES0328#18 0.329,0.329,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
93,88.0,2025-06-05,GHL_pyapp_20250605T1417,Jun5 0.325-0.349mg/mm bag ylw,ES0328#28 0.326,0.326,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
94,89.0,2025-06-05,GHL_pyapp_20250605T1422,Jun5 0.325-0.349mg/mm bag ylw,ES0328#30 0.334,0.334,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,3",NaN
95,90.0,2025-06-05,GHL_pyapp_20250605T1425,Jun5 0.325-0.349mg/mm bag ylw,BluePenES0325#21 0.325,0.325,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
96,91.0,2025-06-05,GHL_pyapp_20250605T1428,Jun5 0.325-0.349mg/mm bag ylw,ES0327#10 0.348,0.348,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
97,92.0,2025-06-05,GHL_pyapp_20250605T1431,Jun5 0.325-0.349mg/mm bag ylw,3-27#29 0.325,0.325,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
98,93.0,2025-06-05,GHL_pyapp_20250605T1437,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0401#3 0.375,0.375,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
99,94.0,2025-06-05,GHL_pyapp_20250605T1440,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0401#10 0.397,0.397,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
100,95.0,2025-06-05,GHL_pyapp_20250605T1443,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0401#13 0.376,0.376,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
101,96.0,2025-06-05,GHL_pyapp_20250605T1447,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0331#37 0.392,0.392,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
102,97.0,2025-06-05,GHL_pyapp_20250605T1450,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0331#34 0.386,0.386,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
103,98.0,2025-06-05,GHL_pyapp_20250605T1454,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0415#18 0.400,0.400,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
104,99.0,2025-06-05,GHL_pyapp_20250605T1457,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0415#14 0.383,0.383,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,3",NaN
105,100.0,2025-06-05,GHL_pyapp_20250605T1522,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0415#21 0.378,0.378,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,3",NaN
106,101.0,2025-06-05,GHL_pyapp_20250605T1528,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0410#22 0.397,0.397,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
107,102.0,2025-06-05,GHL_pyapp_20250605T1532,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0407#8 0.385,0.385,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
108,103.0,2025-06-05,GHL_pyapp_20250605T1536,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0404#2 0.377,0.377,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
109,104.0,2025-06-05,GHL_pyapp_20250605T1539,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0404#10 0.385,0.385,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
110,105.0,2025-06-05,GHL_pyapp_20250605T1542,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#23 0.377,0.377,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
111,106.0,2025-06-05,GHL_pyapp_20250605T1546,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#13 0.398,0.398,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
112,107.0,2025-06-05,GHL_pyapp_20250605T1557,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#12 0.391,0.391,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
113,108.0,2025-06-05,GHL_pyapp_20250605T1600,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#3 0.399,0.399,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
114,109.0,2025-06-05,GHL_pyapp_20250605T1605,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0331#5 0.373,0.373,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
115,110.0,2025-06-05,GHL_pyapp_20250605T1611,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0331#7 0.381,0.381,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
116,111.0,2025-06-05,GHL_pyapp_20250605T1615,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0415#3 0.379,0.379,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
117,112.0,2025-06-05,GHL_pyapp_20250605T1618,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0408#28 0.384,0.384,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
118,113.0,2025-06-05,GHL_pyapp_20250605T1621,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#4 0.392,0.392,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
119,114.0,2025-06-05,GHL_pyapp_20250605T1625,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#1BluMark 0.382,0.382,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,2",NaN
120,115.0,2025-06-05,GHL_pyapp_20250605T1628,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#7 0.383,0.383,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,3",NaN
121,116.0,2025-06-05,GHL_pyapp_20250605T1633,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#14 0.384,0.384,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN
122,117.0,2025-06-05,GHL_pyapp_20250605T1636,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#26 0.398,0.398,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"done,1",NaN

In [11]:
#%% Load OCT study information
octstudies = [];
folder_octexport_root = Path(r'\\file.corp.ghlabs.org\Shared\Projects\NAATOS\V1\NAATOS_OCT_WORK\OCTExport')
#folder_octexport_root = Path(r'D:\SGProjects\NAATOS\OCTlocal')

folder_temp = Path(r'D:\TEMP')

In [12]:
# Load list of data
for idx,record in dffilt.iterrows():
    octstudy = naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder(record['Test name'],folder_octexport_root);
    octstudies.append(octstudy);

STUDY: GHL_pyapp_20250605T1211
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1214
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1218
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1225
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1228
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1233
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1301
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1326
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1330
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1333
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1336
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1340
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1344
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1347
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1350
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1402
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1407
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1410
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1414
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1417
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1422
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1425
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1428
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1431
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1437
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1440
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1443
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1447
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1450
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1454
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1457
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1522
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1528
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1532
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1536
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1539
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1542
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1546
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1557
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1600
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1605
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1611
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1615
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1618
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1621
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1625
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1628
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1633
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1636
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}

# Parse Through The OCTSTUDIES

In [13]:
#%% Load OCTSTUDY object, and start some processing on it
octstudies_to_run = [];
for idx,octstudy in enumerate(octstudies):
    octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder;
    print('~~~~~~~');
    print(octstudy.name);
    pp.pprint(octstudy.resultsCheck())
    doWeRunTheNotebook = any([v is False for k,v in octstudy.resultsCheck().items()])
    print('Run?',doWeRunTheNotebook)
    if(not doWeRunTheNotebook):
        octstudies_to_run.append(octstudy);

    print('~~~~~~~');
    print('We will analyze data for {:} octstudies.'.format(len(octstudies_to_run)))
    print([x.name for x in octstudies_to_run]);

~~~~~~~
GHL_pyapp_20250605T1211
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 1 octstudies.
['GHL_pyapp_20250605T1211']
~~~~~~~
GHL_pyapp_20250605T1214
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 2 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214']
~~~~~~~
GHL_pyapp_20250605T1218
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 3 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218']
~~~~~~~
GHL_pyapp_20250605T1225
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 4 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225']
~~~~~~~
GHL_pyapp_20250605T1228
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 5 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228']
~~~~~~~
GHL_pyapp_20250605T1233
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 6 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233']
~~~~~~~
GHL_pyapp_20250605T1301
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 7 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301']
~~~~~~~
GHL_pyapp_20250605T1326
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 8 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326']
~~~~~~~
GHL_pyapp_20250605T1330
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 9 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330']
~~~~~~~
GHL_pyapp_20250605T1333
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 10 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333']
~~~~~~~
GHL_pyapp_20250605T1336
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 11 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336']
~~~~~~~
GHL_pyapp_20250605T1340
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 12 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340']
~~~~~~~
GHL_pyapp_20250605T1344
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 13 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344']
~~~~~~~
GHL_pyapp_20250605T1347
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 14 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347']
~~~~~~~
GHL_pyapp_20250605T1350
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 15 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350']
~~~~~~~
GHL_pyapp_20250605T1402
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 16 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402']
~~~~~~~
GHL_pyapp_20250605T1407
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 17 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402', 'GHL_pyapp_20250605T1407']
~~~~~~~
GHL_pyapp_20250605T1410
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 18 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402', 'GHL_pyapp_20250605T1407', 'GHL_pyapp_20250605T1410']
~~~~~~~
GHL_pyapp_20250605T1414
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 19 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402', 'GHL_pyapp_20250605T1407', 'GHL_pyapp_20250605T1410', 'GHL_pyapp_20250605T1414']
~~~~~~~
GHL_pyapp_20250605T1417
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 20 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402', 'GHL_pyapp_20250605T1407', 'GHL_pyapp_20250605T1410', 'GHL_pyapp_20250605T1414', 'GHL_pyapp_20250605T1417']
~~~~~~~
GHL_pyapp_20250605T1422
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 21 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402', 'GHL_pyapp_20250605T1407', 'GHL_pyapp_20250605T1410', 'GHL_pyapp_20250605T1414', 'GHL_pyapp_20250605T1417', 'GHL_pyapp_20250605T1422']
~~~~~~~
GHL_pyapp_20250605T1425
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 22 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402', 'GHL_pyapp_20250605T1407', 'GHL_pyapp_20250605T1410', 'GHL_pyapp_20250605T1414', 'GHL_pyapp_20250605T1417', 'GHL_pyapp_20250605T1422', 'GHL_pyapp_20250605T1425']
~~~~~~~
GHL_pyapp_20250605T1428
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 23 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402', 'GHL_pyapp_20250605T1407', 'GHL_pyapp_20250605T1410', 'GHL_pyapp_20250605T1414', 'GHL_pyapp_20250605T1417', 'GHL_pyapp_20250605T1422', 'GHL_pyapp_20250605T1425', 'GHL_pyapp_20250605T1428']
~~~~~~~
GHL_pyapp_20250605T1431
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 24 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402', 'GHL_pyapp_20250605T1407', 'GHL_pyapp_20250605T1410', 'GHL_pyapp_20250605T1414', 'GHL_pyapp_20250605T1417', 'GHL_pyapp_20250605T1422', 'GHL_pyapp_20250605T1425', 'GHL_pyapp_20250605T1428', 'GHL_pyapp_20250605T1431']
~~~~~~~
GHL_pyapp_20250605T1437
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 25 octstudies.

# 1. Load all Data

In [14]:
#octstudies_to_run = [octstudies_to_run[0]]
dfs = [];
for idx,octstudy in enumerate(octstudies_to_run):
    print(octstudy.name)

    #octstudy.load_previously_saved_merged_volume();

    data_extracted = octstudy.load_data_extracted();
    dfstep = octstudy.load_data_extracted_along_strip();
    
    dfstep['octstudy'] = octstudy;

    dfs.append(dfstep)
    #data_extracted = 


    # Calculate Path From Top To Bottom
dfsteps = pd.concat(dfs,keys=[x.name for x in octstudies_to_run]);

GHL_pyapp_20250605T1211
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1214
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1218
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1225
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1228
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1233
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1301
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1326
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1330
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1333
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1336
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1340
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1344
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1347
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1350
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1402
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1407
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1410
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1414
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1417
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1422
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1425
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1428
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1431
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1437
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1440
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1443
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1447
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1450
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1454
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1457
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1522
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1528
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1532
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1536
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1539
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1542
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1546
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1557
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1600
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1605
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1611
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1615
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1618
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1621
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1625
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1628
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1633
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250605T1636
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE

In [9]:
dfsteps

                               pixel_depth_strip_top_sum_threshold  \
                        slice
GHL_pyapp_20250508T1112 5                                57.760000
                        10                               56.800000
                        15                               59.520000
                        20                               56.600000
                        25                               58.080000
...                                                            ...
GHL_pyapp_20250512T1303 8240                             51.040000
                        8245                             51.560000
                        8250                             55.440000
                        8255                             54.120000
                        8260                             53.866667

                               pixel_depth_strip_top  pixel_depth_strip_bot  \
                        slice
GHL_pyapp_20250508T1112 5                        181                    247
                        10                       182                    246
                        15                       183                    244
                        20                       184                    244
                        25                       184                    243
...                                              ...                    ...
GHL_pyapp_20250512T1303 8240                     270                    331
                        8245                     270                    330
                        8250                     270                    328
                        8255                     268                    326
                        8260                     268                    324

                               pixel_depth_wax_center  \
                        slice
GHL_pyapp_20250508T1112 5                         222
                        10                        223
                        15                        226
                        20                        231
                        25                        223
...                                               ...
GHL_pyapp_20250512T1303 8240                      303
                        8245                      303
                        8250                      324
                        8255                      305
                        8260                      297

                                                px_wax_transverse_edges  \
                        slice
GHL_pyapp_20250508T1112 5       (56.33712121212121, 105.00769230769231)
                        10      (56.755319148936174, 105.3936170212766)
                        15       (56.82631578947368, 103.9396551724138)
                        20      (55.68604651162791, 102.38636363636364)
                        25      (53.572463768115945, 102.2843137254902)
...                                                                 ...
GHL_pyapp_20250512T1303 8240               (45.228873239436616, 121.35)
                        8245   (44.877272727272725, 118.78289473684211)
                        8250              (44.430851063829785, 116.775)
                        8255    (44.61702127659574, 112.73170731707317)
                        8260   (44.353932584269664, 112.84482758620689)

                              wax_top_seed_candidate_px  \
                        slice
GHL_pyapp_20250508T1112 5                     (190, 80)
                        10                    (195, 80)
                        15                    (202, 79)
                        20                    (203, 78)
                        25                    (206, 77)
...                                                 ...
GHL_pyapp_20250512T1303 8240                  (288, 83)
                        8245                  (285, 81)
                        8250                  (283, 80)
                        8255                  (284, 78)
                        8260                  (281, 78)

                                                                            pksA  \
                        slice
GHL_pyapp_20250508T1112 5      ([11, 91, 163], {'prominences': [3602.0, 714.0...
                        10     ([15, 60, 90, 124, 162], {'prominences': [4589...
                        15     ([19, 59, 107, 166], {'prominences': [6548.0, ...
                        20     ([19, 58, 110, 166], {'prominences': [6682.0, ...
                        25     ([26, 61, 107, 166], {'prominences': [6172.0, ...
...                                                                          ...
GHL_pyapp_20250512T1303 8240   ([17, 47, 80, 126, 185, 286], {'prominences': ...
                        8245   ([13, 79, 125, 185, 291], {'prominences': [895...
                        8250   ([12, 60, 116, 189, 301], {'prominences': [111...
                        8255   ([13, 61, 114, 163, 302], {'prominences': [135...
                        8260   ([13, 95, 126, 161, 300], {'prominences': [143...

                                                                            pksB  \
                        slice
GHL_pyapp_20250508T1112 5      ([12, 81, 169, 233], {'prominences': [1629.0, ...
                        10     ([15, 82, 163, 233], {'prominences': [3734.0, ...
                        15     ([18, 107, 168, 228, 401], {'prominences': [62...
                        20     ([20, 107, 167, 214], {'prominences': [7049.0,...
                        25     ([25, 106, 169, 205, 385], {'prominences': [83...
...                                                                          ...
GHL_pyapp_20250512T1303 8240   ([18, 125, 184, 235, 285], {'prominences': [10...
                        8245   ([16, 124, 189, 236], {'prominences': [8969.0,...
                        8250   ([14, 116, 189, 236], {'prominences': [8143.0,...
                        8255   ([15, 116, 191, 239], {'prominences': [8920.0,...
                        8260   ([14, 117, 192, 240, 301], {'prominences': [90...

                                                                           pksB2  \
                        slice
GHL_pyapp_20250508T1112 5      ([12, 182, 252], {'peak_heights': [3997.591303...
                        10     ([15, 167, 233], {'peak_heights': [3495.389997...
                        15     ([19, 107, 168, 229], {'peak_heights': [3634.7...
                        20     ([20, 107, 168, 215], {'peak_heights': [2920.4...
                        25     ([25, 169, 205], {'peak_heights': [3135.616720...
...                                                                          ...
GHL_pyapp_20250512T1303 8240   ([18, 186, 236], {'peak_heights': [5377.088794...
                        8245   ([17, 190, 236], {'peak_heights': [5469.765049...
                        8250   ([14, 189, 238], {'peak_heights': [6202.565347...
                        8255   ([15, 191, 239, 302], {'peak_heights': [6012.0...
                        8260   ([14, 193, 240, 302], {'peak_heights': [5243.2...

                               wax_roi_valve_bottom  \
                        slice
GHL_pyapp_20250508T1112 5                       252
                        10                      233
                        15                      229
                        20                      215
                        25                      169
...                                             ...
GHL_pyapp_20250512T1303 8240                    186
                        8245                    190
                        8250                    189
                        8255                    191
                        8260                    193

                                                            testseg_otsu_regions  \
                        slice
GHL_pyapp_20250508T1112 5      [[3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
                        10     [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,...
                        15     [[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 4, 4,...
                        20     [[0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3,...
                        25     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 3, 3,...
...                                                                          ...
GHL_pyapp_20250512T1303 8240   [[0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 4,...
                        8245   [[1, 1, 1, 1, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4,...
                        8250   [[1, 2, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
                        8255   [[1, 1, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 4, 4, 4,...
                        8260   [[0, 0, 0, 0, 0, 0, 1, 2, 2, 3, 4, 4, 4, 4, 4,...

                              testseg_otsu_thresholds  \
                        slice
GHL_pyapp_20250508T1112 5          [59, 93, 135, 196]
                        10        [64, 102, 149, 204]
                        15        [64, 101, 141, 191]
                        20         [55, 86, 123, 177]
                        25         [56, 91, 129, 183]
...                                               ...
GHL_pyapp_20250512T1303 8240       [54, 92, 139, 196]
                        8245       [57, 97, 144, 197]
                        8250       [60, 98, 143, 199]
                        8255       [62, 99, 143, 201]
                        8260      [65, 103, 146, 203]

                               final_wax_bot_subset_px  \
                        slice
GHL_pyapp_20250508T1112 5                          167
                        10                         168
                        15                         168
                        20                         169
                        25                         177
...                                                ...
GHL_pyapp_20250512T1303 8240                       186
                        8245                       190
                        8250                       189
                        8255                       191
                        8260                       193

                                                       seg_thresh_sauvola_cutoff  \
                        slice
GHL_pyapp_20250508T1112 5      [[False, False, False, False, False, False, Fa...
                        10     [[False, False, False, False, False, False, Fa...
                        15     [[False, False, False, False, False, False, Fa...
                        20     [[False, False, False, False, False, False, Fa...
                        25     [[False, False, False, False, False, False, Fa...
...                                                                          ...
GHL_pyapp_20250512T1303 8240   [[False, False, False, False, False, False, Fa...
                        8245   [[False, False, False, False, False, False, Fa...
                        8250   [[False, False, False, False, False, False, Fa...
                        8255   [[False, False, False, False, False, False, Fa...
                        8260   [[False, False, False, False, False, False, Fa...

                                 area  area_filled  area_convex  num_paths  \
                        slice
GHL_pyapp_20250508T1112 5      4535.0       4679.0       5911.0          0
                        10     4969.0       5164.0       6318.0          0
                        15     4838.0       4972.0       6146.0          0
                        20     5005.0       5029.0       6316.0          0
                        25     5255.0       5296.0       7012.0          0
...                               ...          ...          ...        ...
GHL_pyapp_20250512T1303 8240   9195.0       9537.0      12343.0          0
                        8245   8997.0       9396.0      11797.0          0
                        8250   9112.0       9359.0      11628.0          0
                        8255   8313.0       8724.0      10659.0          0
                        8260   8114.0       8847.0      10956.0          0

                                                                        octstudy
                        slice
GHL_pyapp_20250508T1112 5      <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        10     <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        15     <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        20     <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        25     <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
...                                                                          ...
GHL_pyapp_20250512T1303 8240   <OCT_Study_Folder Object>\nGHL_pyapp_20250512T...
                        8245   <OCT_Study_Folder Object>\nGHL_pyapp_20250512T...
                        8250   <OCT_Study_Folder Object>\nGHL_pyapp_20250512T...
                        8255   <OCT_Study_Folder Object>\nGHL_pyapp_20250512T...
                        8260   <OCT_Study_Folder Object>\nGHL_pyapp_20250512T...

[80389 rows x 19 columns]

In [15]:
import gc
gc.collect()

0

## 2. Save

In [16]:
cols_ignore = ['testseg_otsu_thresholds','testseg_otsu_regions','seg_thresh_sauvola_cutoff','pksA','pksB','pksB2']

df = dfsteps[[x for x in dfsteps.columns.tolist() if x not in cols_ignore]]
df.to_hdf(folder_temp/'oct_results_summary_2025_06_10.hdf',key='table');

C:\Users\SimonGhionea\AppData\Local\Temp\ipykernel_49460\4046468293.py:4: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['px_wax_transverse_edges', 'wax_top_seed_candidate_px', 'octstudy'], dtype='object')]

  df.to_hdf(folder_temp/'oct_results_summary_2025_06_10.hdf',key='table');

# handle the source image

In [ ]:
def getSitkImage(octstudy_with_loaded_vdvol):
    # Test getting SITK image
    # Get ITK image without requiring new memory
    import itk
    import vtk

    # function to go from itk image to simpleitk image
    def itkToSimpleITK(itk_image):
        new_sitk_image = sitk.GetImageFromArray(itk.GetArrayViewFromImage(itk_image),isVector=itk_image.GetNumberOfComponentsPerPixel()>1);
        new_sitk_image.SetOrigin(tuple(itk_image.GetOrigin()))
        new_sitk_image.SetSpacing(tuple(itk_image.GetSpacing()))
        new_sitk_image.SetDirection(itk.GetArrayFromMatrix(itk_image.GetDirection()).flatten()) 
        return new_sitk_image;

    print('Get volume for',octstudy_with_loaded_vdvol.name)

    # create simpleitk 3dimage, directly from the previously-loaded vtk 3dimage
    simgmerged = itkToSimpleITK( itk.image_from_vtk_image(octstudy_with_loaded_vdvol.vdvol.dataset) );



    # itk_image
    #print(itk_image)
    slicer_1 = slice( data_extracted['auto_bounds']['topdown_edge_left_px3']  ,  data_extracted['auto_bounds']['topdown_edge_right_px3']  )
    #print(' slicer_dim_0',slicer_0)
    print(' slicer_dim_1',slicer_1)
    #simgmerged.GetSize()
    return simgmerged,{'slicer_1':slicer_1};


simgmerged,voldata = getSitkImage(octstudy);
slicer_1 = voldata['slicer_1'];

In [ ]:
print( simgmerged[:,slicer_1,:] )

In [ ]:
slab_thickness = 10; # px, this was used in the bulk analysis
slice_position_along_strip_px = 4000;
slab_slicer = slice(slice_position_along_strip_px-slab_thickness//2,slice_position_along_strip_px+slab_thickness//2);
simg_slab_img = (simgmerged[:,slicer_1,:])[:,slab_slicer,:]

# 3. Plot Of Values Along Strip

In [ ]:
slice_centers = dfsteps.index;

In [ ]:
simgmerged_summed = sitk.SumProjection(simgmerged[:,slicer_1,:],projectionDimension=0);

In [ ]:
print(simgmerged_summed)

In [ ]:
ndaimg = sitk.GetArrayFromImage(sitk.RescaleIntensity(simgmerged_summed,0,255)); # numpy array

In [ ]:
ndaimg

In [ ]:
#ndaimg = sitk.GetArrayViewFromImage(simgmerged_summed); # numpy array
from PIL import Image
import base64
from io import BytesIO
pil_img = Image.fromarray(ndaimg[:,:,0]) # PIL image object

In [ ]:

ndaimg = sitk.GetArrayViewFromImage(simgmerged_summed); # numpy array
from PIL import Image
import base64
from io import BytesIO
pil_img = Image.fromarray(ndaimg[:,:,0]) # PIL image object

In [ ]:
pil_img.show()

In [ ]:
studyname = dfsteps.index.get_level_values(0).unique().tolist()[1];
octstudy = dfsteps.loc[studyname].iloc[0]['octstudy']

simgmerged,voldata = getSitkImage(octstudy);
slicer_1 = voldata['slicer_1'];
df = dfsteps.loc[studyname,:]

In [ ]:
# Make Detailed Metrics Plots Of 1-Device
import plotly.graph_objects as go
from plotly.subplots import make_subplots

nrows = 5
fig = make_subplots(rows=nrows,shared_xaxes=True,vertical_spacing=0.02, )

slice_centers = df.index;

myrow = 1;
if True:
    # make image
    legendgroup = 'image';

    # use previously created simpleitk merged image filter
    #ndaimg = sitk.GetArrayViewFromImage(simgmerged_summed); # numpy array
    ndaimg = sitk.GetArrayFromImage(sitk.RescaleIntensity(simgmerged_summed,0,255)); # numpy array
    print(ndaimg.shape)
    from PIL import Image
    import base64
    from io import BytesIO
    pil_img = Image.fromarray(ndaimg[:,:,0]) # PIL image object
    pil_img = pil_img.convert("L"); # grayscale image convert, from float
    prefix = "data:image/png;base64,"
    with BytesIO() as stream:
        pil_img.save(stream, format="png")
        base64_string = prefix + base64.b64encode(stream.getvalue()).decode("utf-8")

    fig.add_trace(
        go.Image(
            source=base64_string,
            #cmap='jet',
        ),
        row=myrow,col=1,
    )

legendgroup = 'distances';
myrow+=1;
# Wax Thickness
wax_top = df.loc[slice_centers]['wax_top_seed_candidate_px'].apply(lambda x: x[0]);
#wax_top = dfstepA.loc[final_wax_centers]['pixel_depth_strip_top']
wax_bot = df.loc[slice_centers]['pixel_depth_strip_top']+df.loc[slice_centers]['final_wax_bot_subset_px']
wax_thickness = wax_bot-wax_top
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = wax_thickness,
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_thickness1',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
#fig.update_yaxes(title='Wax Valve Width (pixels)',col=1);


# Wax Thickness
wax_top = df.loc[slice_centers]['wax_top_seed_candidate_px'].apply(lambda x: x[0]);
#wax_top = dfstepA.loc[final_wax_centers]['pixel_depth_strip_top']
wax_bot = df.loc[slice_centers]['pixel_depth_strip_top']+df.loc[slice_centers]['final_wax_bot_subset_px']
wax_thickness = wax_bot-df.loc[slice_centers]['pixel_depth_strip_top']
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = wax_thickness,
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_thickness2',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['px_wax_transverse_edges'].apply(lambda x: np.diff(x)[0]),
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_width_px',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = wax_top,
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_top',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)




legendgroup = 'areas';
myrow+=1;
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled']-df['area'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_holes',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_filled',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_convex',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)


legendgroup = 'ratios';
myrow+=1;
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area']/df['area_filled'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_to_areafilled_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area']/df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_to_areaconvex_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled']/df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_areafilled_to_areaconvex_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

legendgroup = 'counts';
myrow+=1;
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['num_paths'],
        name='crossovers_px_paths',
        legendgroup=legendgroup,
    ),
    row=myrow,col=1,
)
fig.update_yaxes(row=myrow,type='log')

# setup legends per row
for i, yaxis in enumerate(fig.select_yaxes(col=1), 1):
    legend_name = f"legend{i}"
    fig.update_layout({legend_name: dict(y=yaxis.domain[1], yanchor="top")}, showlegend=True)
    fig.update_traces(row=i, legend=legend_name)

fig.update_traces(xaxis='x{:}'.format(nrows))
fig.update_yaxes(title='pixels',row=1);
fig.update_yaxes(title='pixels^2',row=2);
fig.update_yaxes(title='ratios',row=3);
fig.update_yaxes(title='counts',row=4);
fig.update_xaxes(title='distance along strip (px)',row=nrows,col=1);
fig.update_layout(hovermode='x unified',hoversubplots="axis",spikedistance=-1);
#fig = px.imshow(sum_wax_strip_along_length[:,0:]);

fig.show(renderer='browser')
#fig

In [ ]:
fig.update_yaxes(row=1,scaleanchor=None)

In [ ]:
fig.layout

In [ ]:
fig.layout.yaxis5

# Multi-strip Data Viewers

## 5-14-2025 Now

In [ ]:
dfsteps.info()

In [ ]:
from dataclasses import dataclass

# @dataclass
# class row_traces:
#     ylabel : str
#     column_names

In [ ]:
#cols_ignore = ['testseg_otsu_thresholds','testseg_otsu_regions','seg_thresh_sauvola_cutoff','pksA','pksB','pksB2','octstudy']
cols_ignore = ['testseg_otsu_thresholds','testseg_otsu_regions','seg_thresh_sauvola_cutoff','pksA','pksB','pksB2']
dfsteps.iloc[1000][[x for x in dfsteps.columns.tolist() if x not in cols_ignore]]

In [ ]:
cols_ignore = ['testseg_otsu_thresholds','testseg_otsu_regions','seg_thresh_sauvola_cutoff','pksA','pksB','pksB2']

df = dfsteps[[x for x in dfsteps.columns.tolist() if x not in cols_ignore]]
df.to_hdf(folder_temp/'oct_results_summary_2025_06_10.hdf',key='table');

In [ ]:
# strip down columns we will not use below
df = dfsteps[[x for x in dfsteps.columns.tolist() if x not in cols_ignore]];
# join info from spreadsheet
df = pd.merge(df.reset_index(),dffilt,left_on='level_0',right_on='Test name');
df

In [ ]:
dfmelted = pd.melt(frame=df,value_vars=['pixel_depth_strip_top'],id_vars=['Test name','slice'])
dfmelted

In [ ]:

slice_centers = df.index;

# Wax Thickness
wax_top = df.loc[slice_centers]['wax_top_seed_candidate_px'].apply(lambda x: x[0]);
#wax_top = dfstepA.loc[final_wax_centers]['pixel_depth_strip_top']
wax_bot = df.loc[slice_centers]['pixel_depth_strip_top']+df.loc[slice_centers]['final_wax_bot_subset_px']
wax_thickness = wax_bot-wax_top

df['wax_thickness1'] = wax_bot-wax_top;
df['wax_thickness2'] = wax_bot-df.loc[slice_centers]['pixel_depth_strip_top'];
df['wax_width_px'] = df['px_wax_transverse_edges'].apply(lambda x: np.diff(x)[0]);
df['wax_top'] = df['wax_top_seed_candidate_px'].apply(lambda x: x[0]);


df['seg_area'] = df['area'];
df['seg_area_filled'] = df['area_filled'];
df['seg_area_holes'] = df['area_filled']-df['area'];

df['seg_area_to_areafilled'] = df['area']/df['seg_area_filled'];
df['seg_area_to_areaconvex'] = df['area']/df['area_convex'];
df['seg_areafilled_to_areaconvex'] = df['seg_area_filled']/df['area_convex'];

In [ ]:
# # Make Detailed Metrics Plots Of 1-Device
# import plotly.graph_objects as go
# from plotly.subplots import make_subplots

# nrows = 4
# fig = make_subplots(rows=nrows,shared_xaxes=True,vertical_spacing=0.02, )
# #tracelabels

# myrow = 1;
# #px.scatter(df,x='slice',y='wax_thickness1',color='Test name')
# fig1 = px.scatter(df,x='slice',y='wax_width_px',color='Test name')
# fig1.show(renderer='browser')

In [ ]:
trace_labels = [];
trace_info = [];

#trace_colors = [];
import itertools
#cyc_color = itertools.cycle(px.colors.qualitative.Alphabet)
cyc_color = itertools.cycle(px.colors.qualitative.Light24)
df_grouped_by_test = df.groupby('Test name');
for studyname,dfv in df_grouped_by_test:
    print(studyname)
    df1 = dfv.iloc[0];
    
    octstudy = df1['octstudy']

    trace_labels.append( octstudy.name )
    #trace_colors.append( next(cyc_color) );
    trace_info.append(
        dict(
            octstudyname = octstudy.name,
            
            tracelabel = octstudy.name,
            tracecolor = next(cyc_color),
        )
    )

In [ ]:
# Make Detailed Metrics Plots Of 1-Device
import plotly.graph_objects as go
from plotly.subplots import make_subplots

#metrics_to_show = ['wax_width_px','seg_area','seg_area_holes','wax_thickness2'];
metrics_to_show = ['wax_width_px','seg_area_to_areafilled','num_paths'];
nrows = len(metrics_to_show)
fig = make_subplots(rows=nrows,shared_xaxes=True,vertical_spacing=0.02, )

myrow = 0;

#legendgroup = 'distances';
for metric_col_name in metrics_to_show:
    myrow+=1;
    
    if True:
        for this_trace_info in trace_info:
            dfv = df_grouped_by_test.get_group(this_trace_info['octstudyname'])

            datax = dfv['slice'];
            datay = dfv[metric_col_name]

            fig.add_trace(
                go.Scattergl(
                    x = datax,
                    y = datay,
                    mode='markers',
                    #type = 'heatmap',
                    #colorscale = 'jet'
                    name=this_trace_info['tracelabel'],
                    marker_color=this_trace_info['tracecolor'],
                    legendgroup=this_trace_info['tracelabel'],
                    showlegend=myrow==1,
                    hoverinfo='name',
                    visible='legendonly',
                ),
                row=myrow,col=1,
            )
    
    fig.update_yaxes(title=metric_col_name,row=myrow);

    if False:
        figtmp = px.scatter(df,x='slice',y=metric_col_name,color='Test name')
        fig.add_traces(figtmp.data,rows=myrow,cols=1);

    #break;




# # setup legends per row
# for i, yaxis in enumerate(fig.select_yaxes(col=1), 1):
#     legend_name = f"legend{i}"
#     fig.update_layout({legend_name: dict(y=yaxis.domain[1], yanchor="top")}, showlegend=True)
#     fig.update_traces(row=i, legend=legend_name)
fig.update_traces(marker_size=4)
fig.update_layout(legend_tracegroupgap=0)

fig.update_traces(xaxis='x{:}'.format(nrows))

# fig.update_yaxes(title='pixels',row=1);
# fig.update_yaxes(title='pixels^2',row=2);
# fig.update_yaxes(title='ratios',row=3);
# fig.update_yaxes(title='counts',row=4);

fig.update_xaxes(title='distance along strip (px)',row=nrows,col=1);

#fig.update_layout(hovermode='x',hoversubplots="axis",spikedistance=-1);
#fig.update_layout(hovermode='x unified',spikedistance=-1,hoverdistance=5);
fig.update_xaxes(showspikes=True, spikesnap="cursor", spikemode="across")

#fig = px.imshow(sum_wax_strip_along_length[:,0:]);

fig.show(renderer='browser')
#fig

## Single-Device Detail

In [ ]:
#df = df_grouped_by_test.get_group('GHL_pyapp_20250512T1245')
df = df_grouped_by_test.get_group('GHL_pyapp_20250508T1158')
df

In [ ]:
metric_traces = [
    ('distances','pixels',['wax_top','wax_thickness1','wax_thickness2','wax_width_px']),
    ('areas','pixels^2',['area','area_filled','area_convex','seg_area_holes']),
    ('ratios','ratio',['seg_area_to_areafilled','seg_area_to_areaconvex','seg_areafilled_to_areaconvex']),
    ('counts','counts',['num_paths']),
]

In [ ]:
# Make Detailed Metrics Plots Of 1-Device
import plotly.graph_objects as go
from plotly.subplots import make_subplots

nrows = len(metric_traces);
fig = make_subplots(rows=nrows,shared_xaxes=True,vertical_spacing=0.02)

myrow = 0;
for legendgroup,ylabel,metric_columns in metric_traces:
    myrow += 1;

    datax = df['slice'];
    for metric_col in metric_columns:
        datay = df[metric_col];

        if(ylabel!='counts'):
            fig.add_trace(
                go.Scattergl(
                    x = datax,
                    y = datay,
                    mode='markers',
                    #type = 'heatmap',
                    #colorscale = 'jet'
                    name=metric_col,
                    #marker_color=this_trace_info['tracecolor'],
                    legendgroup=legendgroup,
                    legendgrouptitle={'text': legendgroup},
                    #showlegend=myrow==1,
                    #hoverinfo='name',
                    #visible='legendonly',
                ),
                row=myrow,col=1,
            )
        else:
            fig.add_trace(
                go.Bar(
                    x = datax,
                    y = datay,
                    #mode='markers',
                    #type = 'heatmap',
                    #colorscale = 'jet'
                    name=metric_col,
                    #marker_color=this_trace_info['tracecolor'],
                    legendgroup=legendgroup,
                    legendgrouptitle={'text': legendgroup},
                    #showlegend=myrow==1,
                    #hoverinfo='name',
                    #visible='legendonly',
                ),
                row=myrow,col=1,
            )

    
    fig.update_yaxes(title=ylabel,row=myrow);
    if(ylabel=='counts'):
        fig.update_yaxes(type='log',row=myrow);

# setup legends per row
for i, yaxis in enumerate(fig.select_yaxes(col=1), 1):
    legend_name = f"legend{i}"
    fig.update_layout({legend_name: dict(y=yaxis.domain[1], yanchor="top")}, showlegend=True)
    fig.update_traces(row=i, legend=legend_name)

fig.update_xaxes(title='distance along strip (px)',row=nrows,col=1);

fig.update_traces(xaxis='x{:}'.format(nrows))
fig.update_layout(hovermode='x unified',spikedistance=-1,hoverdistance=5);
#fig.update_yaxes(title='pixels',row=1);
fig.show(renderer='browser')

In [ ]:
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area']/df['area_filled'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_to_areafilled_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area']/df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_to_areaconvex_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled']/df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_areafilled_to_areaconvex_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

In [ ]:
#ndaimg = sitk.GetArrayViewFromImage(simgmerged_summed); # numpy array
from PIL import Image
import base64
from io import BytesIO
pil_img = Image.fromarray(ndaimg[:,:,0]) # PIL image object

In [ ]:

ndaimg = sitk.GetArrayViewFromImage(simgmerged_summed); # numpy array
from PIL import Image
import base64
from io import BytesIO
pil_img = Image.fromarray(ndaimg[:,:,0]) # PIL image object

In [ ]:
pil_img.show()

In [ ]:
studyname = dfsteps.index.get_level_values(0).unique().tolist()[1];
octstudy = dfsteps.loc[studyname].iloc[0]['octstudy']

simgmerged,voldata = getSitkImage(octstudy);
slicer_1 = voldata['slicer_1'];
df = dfsteps.loc[studyname,:]

In [ ]:
# Make Detailed Metrics Plots Of 1-Device
import plotly.graph_objects as go
from plotly.subplots import make_subplots

nrows = 5
fig = make_subplots(rows=nrows,shared_xaxes=True,vertical_spacing=0.02, )

slice_centers = df.index;

myrow = 1;
if False:
    # make image
    legendgroup = 'image';

    # use previously created simpleitk merged image filter
    #ndaimg = sitk.GetArrayViewFromImage(simgmerged_summed); # numpy array
    ndaimg = sitk.GetArrayFromImage(sitk.RescaleIntensity(simgmerged_summed,0,255)); # numpy array
    print(ndaimg.shape)
    from PIL import Image
    import base64
    from io import BytesIO
    pil_img = Image.fromarray(ndaimg[:,:,0]) # PIL image object
    pil_img = pil_img.convert("L"); # grayscale image convert, from float
    prefix = "data:image/png;base64,"
    with BytesIO() as stream:
        pil_img.save(stream, format="png")
        base64_string = prefix + base64.b64encode(stream.getvalue()).decode("utf-8")

    fig.add_trace(
        go.Image(
            source=base64_string,
            #cmap='jet',
        ),
        row=myrow,col=1,
    )

legendgroup = 'distances';
myrow+=1;
# Wax Thickness
wax_top = df.loc[slice_centers]['wax_top_seed_candidate_px'].apply(lambda x: x[0]);
#wax_top = dfstepA.loc[final_wax_centers]['pixel_depth_strip_top']
wax_bot = df.loc[slice_centers]['pixel_depth_strip_top']+df.loc[slice_centers]['final_wax_bot_subset_px']
wax_thickness = wax_bot-wax_top
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = wax_thickness,
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_thickness1',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
#fig.update_yaxes(title='Wax Valve Width (pixels)',col=1);


# Wax Thickness
wax_top = df.loc[slice_centers]['wax_top_seed_candidate_px'].apply(lambda x: x[0]);
#wax_top = dfstepA.loc[final_wax_centers]['pixel_depth_strip_top']
wax_bot = df.loc[slice_centers]['pixel_depth_strip_top']+df.loc[slice_centers]['final_wax_bot_subset_px']
wax_thickness = wax_bot-df.loc[slice_centers]['pixel_depth_strip_top']
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = wax_thickness,
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_thickness2',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['px_wax_transverse_edges'].apply(lambda x: np.diff(x)[0]),
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_width_px',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = wax_top,
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_top',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)




legendgroup = 'areas';
myrow+=1;
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled']-df['area'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_holes',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_filled',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_convex',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)


legendgroup = 'ratios';
myrow+=1;
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area']/df['area_filled'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_to_areafilled_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area']/df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_to_areaconvex_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled']/df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_areafilled_to_areaconvex_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

legendgroup = 'counts';
myrow+=1;
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['num_paths'],
        name='crossovers_px_paths',
        legendgroup=legendgroup,
    ),
    row=myrow,col=1,
)
fig.update_yaxes(row=myrow,type='log')

# setup legends per row
for i, yaxis in enumerate(fig.select_yaxes(col=1), 1):
    legend_name = f"legend{i}"
    fig.update_layout({legend_name: dict(y=yaxis.domain[1], yanchor="top")}, showlegend=True)
    fig.update_traces(row=i, legend=legend_name)

fig.update_traces(xaxis='x{:}'.format(nrows))
fig.update_yaxes(title='pixels',row=1);
fig.update_yaxes(title='pixels^2',row=2);
fig.update_yaxes(title='ratios',row=3);
fig.update_yaxes(title='counts',row=4);
fig.update_xaxes(title='distance along strip (px)',row=nrows,col=1);
fig.update_layout(hovermode='x unified',hoversubplots="axis",spikedistance=-1);
#fig = px.imshow(sum_wax_strip_along_length[:,0:]);

fig.show(renderer='browser')
#fig