# Process Multiple Long Strips

In [1]:
#%% imports
from pathlib import Path
# import json
# import configparser
import pprint
pp = pprint.PrettyPrinter(indent=4);
import time
import math
from collections import namedtuple

# # pip install slicerio
# import slicerio.server

# # packages for 3d
# #   # for OCT 3D stuff and using in jupyter
# #   - trame-jupyter-extension
# #   - trame
# #   - trame-vtk
# #   - trame-vuetify
# #   - ipywidgets

import matplotlib.pyplot as plt
import plotly.express as px

# interactive panels
import panel as pn
pn.extension('plotly');

import numpy as np
import pandas as pd
import addict

import cv2
import skimage
import scipy.signal

import pyvista as pv
from PIL import Image
import SimpleITK as sitk

# with vedo
#from vedo import dataurl, Volume, Text2D
import vedo
vedo.settings.default_backend = 'vtk'
#from vedo.applications import Slicer3DPlotter
import naatos_oct_tools.plotters.vedo_plotters as vedo_plotters
import naatos_oct_tools.plotters.sitk_plotters as sitk_plotters

import naatos_oct_tools.thorlabs_oct_file_reading
import naatos_oct_tools.oct_linear_scan_processing

import papermill

In [2]:
# Magics to autoreload submodules when they are modified
%load_ext autoreload
%autoreload 2

In [3]:
#%% Test Record Excel
fname_excel = r'C:\Users\SimonGhionea\Global Health Labs, Inc\NAATOS Product Feasibility - TB V1 - General - Internal - Wax Valve\OCT\Test\OCT_wax_valve_test_record.xlsx';
dftests = pd.read_excel(
    fname_excel,
    skiprows=1
)
dftests = dftests.iloc[:,1:]
dftests.rename(columns={'Unnamed: 19':'Notes'},inplace=True)
dftests

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Unnamed: 24
0,NaN,2025-03-26,GHL_pyapp_20250326T1258,oven aging test day 1,strip 7,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025-03-26,GHL_pyapp_20250326T1403,oven aging test day 1,strip 10,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2025-03-26,GHL_pyapp_20250326T1416,oven aging test day 1,strip 14,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2025-03-27,GHL_pyapp_20250327T1428,oven aging test day 2,strip 7,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2025-03-27,GHL_pyapp_20250327T1438,oven aging test day 2,strip 10,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,64.0,2025-05-12,GHL_pyapp_20250512T1258,0.350-0.374mg/mm lrg bag blu,ES0331#33 0.373,0.373,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runD,Simon
70,65.0,2025-05-12,GHL_pyapp_20250512T1303,0.350-0.374mg/mm lrg bag blu,ES0414#1 0.353,0.353,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runD,Simon
71,66.0,2025-05-12,GHL_pyapp_20250512T1341,Valves ES 4/16/2024 1-sided no reflo,#1,NaN,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,trimmed ends to fit
72,67.0,2025-05-12,GHL_pyapp_20250512T1350,Valves ES 4/16/2024 1-sided no reflo,#2,NaN,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,trimmed ends to fit
73,68.0,2025-05-12,GHL_pyapp_20250512T1415,Valves ES 4/16/2024 1-sided no reflo,#3,NaN,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,trimmed ends to fit

In [6]:
#%% Filter The Tests To Process
# dfmasks = [
#     (dftests['Test date']<'2025-03-28') & (dftests['Test date']>='2025-03-26'),
#     dftests['Test name'] != 'GHL_pyapp_20250326T1258'
# ]
# dfmasks = [
#     (dftests['Test date']<='2025-04-15') & (dftests['Test date']>='2025-04-14')
# ]
# dfmasks = [
#     dftests['Test date']=='2025-05-05',
# ]
# dfmasks = [
#     dftests['Test date']=='2025-05-08',
# ]
dfmasks = [
    dftests['Test date']=='2025-05-12',
    ~dftests['Batch'].str.contains('Valves ES')
]

dffilt = dftests[np.all(dfmasks,axis=0)]
dffilt

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Unnamed: 24
38,33.0,2025-05-12,GHL_pyapp_20250512T0947,0.350-0.374mg/mm lrg bag blu,ES0414#7 0.367,0.367,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem run,Simon
39,34.0,2025-05-12,GHL_pyapp_20250512T0951,0.350-0.374mg/mm lrg bag blu,ES0414#5 0.352,0.352,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem run,Simon
40,35.0,2025-05-12,GHL_pyapp_20250512T0955,0.350-0.374mg/mm lrg bag blu,ES0415#8 0.351,0.351,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem run,Simon
41,36.0,2025-05-12,GHL_pyapp_20250512T0959,0.350-0.374mg/mm lrg bag blu,ES0408#16 0.372,0.372,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem run,Simon
42,37.0,2025-05-12,GHL_pyapp_20250512T1002,0.350-0.374mg/mm lrg bag blu,ES0409#7 0.366,0.366,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem run,Simon
43,38.0,2025-05-12,GHL_pyapp_20250512T1117,0.350-0.374mg/mm lrg bag blu,ES0410#2 0.372,0.372,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runC,Simon
44,39.0,2025-05-12,GHL_pyapp_20250512T1121,0.350-0.374mg/mm lrg bag blu,ES0415#30 0.359,0.359,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runC,Simon
45,40.0,2025-05-12,GHL_pyapp_20250512T1125,0.350-0.374mg/mm lrg bag blu,ES0415#27 0.354,0.354,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runC,Simon
46,41.0,2025-05-12,GHL_pyapp_20250512T1130,0.350-0.374mg/mm lrg bag blu,ES0415#26 0.374,0.374,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runC,Simon
47,42.0,2025-05-12,GHL_pyapp_20250512T1133,0.350-0.374mg/mm lrg bag blu,ES0415#22 0.366,0.366,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runC,Simon
48,43.0,2025-05-12,GHL_pyapp_20250512T1137,0.350-0.374mg/mm lrg bag blu,ES0403#22 0.351,0.351,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem runB,Simon
49,44.0,2025-05-12,GHL_pyapp_20250512T1140,0.350-0.374mg/mm lrg bag blu,ES0403#37 0.372,0.372,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem runB,Simon
50,45.0,2025-05-12,GHL_pyapp_20250512T1144,0.350-0.374mg/mm lrg bag blu,ES0404#5 0.352,0.352,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem runB,Simon
51,46.0,2025-05-12,GHL_pyapp_20250512T1149,0.350-0.374mg/mm lrg bag blu,ES0407#7 0.384,0.384,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem runB,Simon
52,47.0,2025-05-12,GHL_pyapp_20250512T1152,0.350-0.374mg/mm lrg bag blu,ES0407#9 0.372,0.372,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem runB,Simon
53,48.0,2025-05-12,GHL_pyapp_20250512T1158,0.350-0.374mg/mm lrg bag blu,ES0403#15 0.363,0.363,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem runB,Simon
54,49.0,2025-05-12,GHL_pyapp_20250512T1201,0.350-0.374mg/mm lrg bag blu,ES0403#14 0.363,0.363,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rem runB,Simon
55,50.0,2025-05-12,GHL_pyapp_20250512T1204,0.350-0.374mg/mm lrg bag blu,ES0403#20 0.371,0.371,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runF DONE but REDO bounds,Simon
56,51.0,2025-05-12,GHL_pyapp_20250512T1208,0.350-0.374mg/mm lrg bag blu,ES0408#23 0.364,0.364,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runF,Simon
57,52.0,2025-05-12,GHL_pyapp_20250512T1211,0.350-0.374mg/mm lrg bag blu,ES0331#50 0.374,0.374,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runF,Simon
58,53.0,2025-05-12,GHL_pyapp_20250512T1215,0.350-0.374mg/mm lrg bag blu,ES0402#4 0.368,0.368,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runF,Simon
59,54.0,2025-05-12,GHL_pyapp_20250512T1218,0.350-0.374mg/mm lrg bag blu,ES0402#13 0.355,0.355,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runF,Simon
60,55.0,2025-05-12,GHL_pyapp_20250512T1222,0.350-0.374mg/mm lrg bag blu,ES0402#23 0.363,0.363,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runF,Simon
61,56.0,2025-05-12,GHL_pyapp_20250512T1225,0.350-0.374mg/mm lrg bag blu,ES0331#43 0.351,0.351,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runF,Simon
62,57.0,2025-05-12,GHL_pyapp_20250512T1230,0.350-0.374mg/mm lrg bag blu,ES401#5 0.354,0.354,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runF,Simon
63,58.0,2025-05-12,GHL_pyapp_20250512T1238,0.350-0.374mg/mm lrg bag blu,ES0402#6 0.372,0.372,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runF,Simon
64,59.0,2025-05-12,GHL_pyapp_20250512T1241,0.350-0.374mg/mm lrg bag blu,ES0402#9 0.372,0.372,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runE,Simon
65,60.0,2025-05-12,GHL_pyapp_20250512T1245,0.350-0.374mg/mm lrg bag blu,ES0402#10 0.358,0.358,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runE,Simon dropped on floor before loading
66,61.0,2025-05-12,GHL_pyapp_20250512T1248,0.350-0.374mg/mm lrg bag blu,ES0401#2 0.358,0.358,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runE,Simon1
67,62.0,2025-05-12,GHL_pyapp_20250512T1251,0.350-0.374mg/mm lrg bag blu,ES0401#20 0.358,0.358,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runE,Simon
68,63.0,2025-05-12,GHL_pyapp_20250512T1254,0.350-0.374mg/mm lrg bag blu,ES0331#36 0.355,0.355,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runD,Simon
69,64.0,2025-05-12,GHL_pyapp_20250512T1258,0.350-0.374mg/mm lrg bag blu,ES0331#33 0.373,0.373,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runD,Simon
70,65.0,2025-05-12,GHL_pyapp_20250512T1303,0.350-0.374mg/mm lrg bag blu,ES0414#1 0.353,0.353,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loc runD,Simon

In [7]:
#%% Load OCT study information
octstudies = [];
folder_octexport_root = Path(r'\\file.corp.ghlabs.org\Shared\Projects\NAATOS\V1\NAATOS_OCT_WORK\OCTExport')
#folder_octexport_root = Path(r'D:\SGProjects\NAATOS\OCTlocal')

# Load list of data
for idx,record in dffilt.iterrows():
    octstudy = naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder(record['Test name'],folder_octexport_root);
    octstudies.append(octstudy);

STUDY: GHL_pyapp_20250512T0947
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T0951
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T0955
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T0959
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1002
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1117
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1121
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1125
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1130
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1133
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1137
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1140
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1144
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1149
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1152
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1158
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1201
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1204
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1208
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1211
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1215
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1218
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1222
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1225
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1230
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1238
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1241
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1245
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1248
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1251
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1254
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1258
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1303
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}

# Manipulate excel directly

In [8]:
import openpyxl

workbook = openpyxl.load_workbook(fname_excel);

In [9]:
sheet = workbook.active

In [10]:
hdrrow = 2;
hdrcols = sheet[hdrrow];
print(hdrcols)
hdr = {c.value:cnt+1 for cnt,c in enumerate(hdrcols)};
print(hdr)

(<Cell 'Strip measurement'.A2>, <Cell 'Strip measurement'.B2>, <Cell 'Strip measurement'.C2>, <Cell 'Strip measurement'.D2>, <Cell 'Strip measurement'.E2>, <Cell 'Strip measurement'.F2>, <Cell 'Strip measurement'.G2>, <Cell 'Strip measurement'.H2>, <Cell 'Strip measurement'.I2>, <Cell 'Strip measurement'.J2>, <Cell 'Strip measurement'.K2>, <Cell 'Strip measurement'.L2>, <Cell 'Strip measurement'.M2>, <Cell 'Strip measurement'.N2>, <Cell 'Strip measurement'.O2>, <Cell 'Strip measurement'.P2>, <Cell 'Strip measurement'.Q2>, <Cell 'Strip measurement'.R2>, <Cell 'Strip measurement'.S2>, <Cell 'Strip measurement'.T2>, <Cell 'Strip measurement'.U2>, <Cell 'Strip measurement'.V2>, <Cell 'Strip measurement'.W2>, <Cell 'Strip measurement'.X2>, <Cell 'Strip measurement'.Y2>)
{None: 25, 'Test ID': 2, 'Test date': 3, 'Test name': 4, 'Batch': 5, 'Strip': 6, 'Wax (mg/mm)': 7, 'Fixture': 8, 'X, FOV': 9, 'Y, FOV': 10, 'Z, FOV': 11, 'X, pixel size': 12, 'Y, pixel size': 13, 'Z, pixel size': 14, 'Angle': 15, 'Right edge (mm)': 16, 'Left edge (mm)': 17, 'Strip length (mm)': 18, 'Speed/Sensitivity': 19, 'Averaging (A-scan)': 20, 'Refractive Index': 21, 'File size (MB)': 22, 'Total size (GB)': 23, 'ProcessingNotes': 24}

In [15]:
for row in sheet.iter_rows(min_row=hdrrow+3,min_col=hdrcols[0].column):
    record = {hdrcols[cnt].value:c.value for cnt,c in enumerate(row)}
    matchingoctstudy = [octstudy for octstudy in octstudies if octstudy.name==record["Test name"]]
    if len(matchingoctstudy)==1:
        print(record)
        print(octstudy.name)
        octstudy = matchingoctstudy[0]
        octstudy.load_first_oct();
        octdata = octstudy.octdatalist[0]
        cfg_oct_xml = octdata.cfg_oct_xml;

        # populate filesize
        row[hdr['Total size (GB)']-1].value = round(sum([f.stat().st_size for f in octstudy.folder_study.glob('*.oct')])/1e9,2);
        row[hdr['File size (MB)']-1].value = round((sum([f.stat().st_size for f in octstudy.folder_study.glob('*.oct')])/1e9)/octstudy.num_oct_files,2);

        # populate acquisition details
        pixelsize_x = float(cfg_oct_xml.Ocity.Image.PixelSpacing.SizeX.etElem.text)
        pixelsize_y = float(cfg_oct_xml.Ocity.Image.PixelSpacing.SizeY.etElem.text)
        pixelsize_z = float(cfg_oct_xml.Ocity.Image.PixelSpacing.SizeZ.etElem.text)
        totalsizemm_x = float(cfg_oct_xml.Ocity.Image.SizeReal.SizeX.etElem.text)
        totalsizemm_y = float(cfg_oct_xml.Ocity.Image.SizeReal.SizeY.etElem.text)
        totalsizemm_z = float(cfg_oct_xml.Ocity.Image.SizeReal.SizeZ.etElem.text)
        row[hdr['X, FOV']-1].value = totalsizemm_x;
        row[hdr['Y, FOV']-1].value = totalsizemm_y;
        row[hdr['Z, FOV']-1].value = totalsizemm_z;
        row[hdr['X, pixel size']-1].value = pixelsize_x*1e3;
        row[hdr['Y, pixel size']-1].value = pixelsize_y*1e3;
        row[hdr['Z, pixel size']-1].value = pixelsize_z*1e3;
        row[hdr['Angle']-1].value = float(cfg_oct_xml.Ocity.Image.Angle.etElem.text)
        row[hdr['Speed/Sensitivity']-1].value = cfg_oct_xml.Ocity.Instrument.DevicePresetDescription.etElem.text;
        row[hdr['Averaging (A-scan)']-1].value = int(cfg_oct_xml.Ocity.Acquisition.IntensityAveraging.AScans.etElem.text)
        row[hdr['Refractive Index']-1].value = round(float(cfg_oct_xml.Ocity.Acquisition.RefractiveIndex.etElem.text),1);

        if octstudy.has_json_info_file:
            jsoninfo = octstudy.json_info_file;
            row[hdr['Left edge (mm)']-1].value = jsoninfo['pos_leftmost_edge_center'];
            row[hdr['Right edge (mm)']-1].value = jsoninfo['pos_rightmost_edge_center'];
            row[hdr['Strip length (mm)']-1].value = jsoninfo['pos_rightmost_edge_center']-jsoninfo['pos_leftmost_edge_center'];

        rescheck = octstudy.resultsCheck();
        haveAllResults = not all([v is False for k,v in rescheck.items()])
        #haveAllResults = haveAllResults and (len(rescheck['along_strip_data_extracted'])==5)
        print('results done?',haveAllResults)
        if(haveAllResults):
            row[hdr['ProcessingNotes']-1].value = 'done,{:d}'.format(len(rescheck['along_strip_data_extracted']))
        else:
            row[hdr['ProcessingNotes']-1].value = ''
        #break

    #octstudy.octdatalist[0]

{None: 'Simon', 'Test ID': 33, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T0947', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0414#7 0.367', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F41, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816383999999997, 'Total size (GB)': 4.14511296, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1303
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 34, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T0951', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0414#5 0.352', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F42, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21815895752631578, 'Total size (GB)': 4.145020193, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T0947
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 35, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T0955', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0415#8 0.351', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F43, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21817336405263157, 'Total size (GB)': 4.145293917, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T0951
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 36, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T0959', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0408#16 0.372', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F44, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.2181578134736842, 'Total size (GB)': 4.144998456, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T0955
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 37, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1002', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0409#7 0.366', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F45, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816489389473684, 'Total size (GB)': 4.145132984, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T0959
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 38, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1117', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0410#2 0.372', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F46, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.2181538322105263, 'Total size (GB)': 4.144922812, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1002
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 39, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1121', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0415#30 0.359', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F47, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21815516715789474, 'Total size (GB)': 4.144948176, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1117
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 40, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1125', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0415#27 0.354', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F48, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816735510526317, 'Total size (GB)': 4.145179747, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1121
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 41, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1130', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0415#26 0.374', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F49, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816042742105266, 'Total size (GB)': 4.145048121, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1125
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 42, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1133', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0415#22 0.366', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F50, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816727889473686, 'Total size (GB)': 4.145178299, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1130
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 43, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1137', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0403#22 0.351', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F51, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816198705263157, 'Total size (GB)': 4.145077754, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1133
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 44, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1140', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0403#37 0.372', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F52, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.218170002, 'Total size (GB)': 4.145230038, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1137
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 45, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1144', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0404#5 0.352', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F53, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816672973684212, 'Total size (GB)': 4.145167865, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1140
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 46, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1149', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0407#7 0.384', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F54, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816025063157896, 'Total size (GB)': 4.145044762, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1144
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 47, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1152', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0407#9 0.372', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F55, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21815418863157893, 'Total size (GB)': 4.144929584, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1149
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 48, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1158', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0403#15 0.363', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F56, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21815765036842105, 'Total size (GB)': 4.144995357, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1152
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 49, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1201', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0403#14 0.363', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F57, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.2181619380526316, 'Total size (GB)': 4.145076823, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1158
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 50, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1204', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0403#20 0.371', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F58, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816939921052633, 'Total size (GB)': 4.145218585, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1201
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 51, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1208', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0408#23 0.364', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F59, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21817106668421052, 'Total size (GB)': 4.145250267, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1204
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 52, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1211', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0331#50 0.374', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F60, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21815470789473684, 'Total size (GB)': 4.14493945, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1208
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 53, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1215', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0402#4 0.368', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F61, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816872184210528, 'Total size (GB)': 4.145205715, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1211
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 54, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1218', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0402#13 0.355', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F62, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21816232347368422, 'Total size (GB)': 4.145084146, 'ProcessingNotes': 'done,5'}
GHL_pyapp_20250512T1215
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? True
{None: 'Simon', 'Test ID': 55, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1222', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0402#23 0.363', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F63, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.2181589437894737, 'Total size (GB)': 4.145019932, 'ProcessingNotes': ''}
GHL_pyapp_20250512T1218
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? False
{None: 'Simon', 'Test ID': 56, 'Test date': datetime.datetime(2025, 5, 12, 0, 0), 'Test name': 'GHL_pyapp_20250512T1225', 'Batch': '0.350-0.374mg/mm lrg bag blu', 'Strip': 'ES0331#43 0.351', 'Wax (mg/mm)': '=_xlfn.NUMBERVALUE(_xlfn.TEXTAFTER(F64, " "))', 'Fixture': 'Vacuum', 'X, FOV': 9.0, 'Y, FOV': 3.5, 'Z, FOV': 2.39775, 'X, pixel size': 20.0, 'Y, pixel size': 20.0, 'Z, pixel size': 3.4749999999999996, 'Angle': 0.0, 'Right edge (mm)': 308.5, 'Left edge (mm)': 143.0, 'Strip length (mm)': 165.5, 'Speed/Sensitivity': 'Default (Medium sensitivity, 48 kHz)', 'Averaging (A-scan)': 2, 'Refractive Index': None, 'File size (MB)': 0.21815727089473685, 'Total size (GB)': 4.144988147, 'ProcessingNotes': ''}
GHL_pyapp_20250512T1222
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
results done? False

In [14]:
round(float(cfg_oct_xml.Ocity.Acquisition.RefractiveIndex.etElem.text),1)

1.6

In [18]:
hdr

{None: 24,
 'Test ID': 2,
 'Test date': 3,
 'Test name': 4,
 'Batch': 5,
 'Strip': 6,
 'Wax (mg/mm)': 7,
 'Fixture': 8,
 'X, FOV': 9,
 'Y, FOV': 10,
 'Z, FOV': 11,
 'X, pixel size': 12,
 'Y, pixel size': 13,
 'Z, pixel size': 14,
 'Angle': 15,
 'Right edge (mm)': 16,
 'Left edge (mm)': 17,
 'Strip length (mm)': 18,
 'Speed/Sensitivity': 19,
 'Averaging (A-scan)': 20,
 'File size (MB)': 21,
 'Total size (GB)': 22,
 'ProcessingNotes': 23}

In [28]:
len(octstudy.resultsCheck()['along_strip_data_extracted'])==5

True

In [48]:
from xml.etree import ElementTree
ElementTree.dump(cfg_oct_xml.getroot())

<Ocity version="1.0">
    <DataFiles>
        <DataFile Type="Colored" SizeZ="648" SizeX="484" RangeZ="648" RangeX="484" RangeY="1" BytesPerPixel="4">data\VideoImage.data</DataFile>
        <DataFile Type="Colored" SizeZ="640" SizeX="480" RangeZ="1" RangeX="1" RangeY="1" BytesPerPixel="4">data\PreviewImage.data</DataFile>
        <DataFile Type="Real" SizeZ="690" SizeX="450" SizeY="175" RangeZ="1.4985937499999997" RangeX="9" RangeY="3.5" BytesPerPixel="4">data\Intensity.data</DataFile>
        <DataFile Type="Text">data\Probe.ini</DataFile>
    </DataFiles>
    <Image Type="Processed">
        <SizePixel Unit="px">
            <SizeZ>690</SizeZ>
            <SizeX>450</SizeX>
            <SizeY>175</SizeY>
        </SizePixel>
        <SizeReal Unit="mm">
            <SizeZ>2.397750</SizeZ>
            <SizeX>9.000000</SizeX>
            <SizeY>3.500000</SizeY>
        </SizeReal>
        <PixelSpacing>
            <SizeZ>0.003475</SizeZ>
            <SizeX>0.020000</SizeX>
            <SizeY>0.020000</SizeY>
        </PixelSpacing>
        <DataType>float</DataType>
        <AxisOrder>ZXYT</AxisOrder>
        <CenterX>0.000000</CenterX>
        <CenterY>0.100000</CenterY>
        <Angle>0.000000</Angle>
        <Zoom>1.000000</Zoom>
        <FreeformScanPatternIsActive>False</FreeformScanPatternIsActive>
        <FreeformScanPatternCloseLoop>False</FreeformScanPatternCloseLoop>
        <FreeformScanPatternInterpolation>linear</FreeformScanPatternInterpolation>
        <MinPointDistance>0.000000</MinPointDistance>
        <MaxPointDistance>0.000000</MaxPointDistance>
    </Image>
    <Acquisition>
        <IntensityAveraging>
            <Spectra>1</Spectra>
            <AScans>2</AScans>
            <BScans>1</BScans>
        </IntensityAveraging>
        <DopplerAveraging>
            <PixelsX>2</PixelsX>
            <PixelsZ>1</PixelsZ>
            <Oversampling>False</Oversampling>
        </DopplerAveraging>
        <DopplerAngle>
            <Degrees>0.000000</Degrees>
        </DopplerAngle>
        <SpeckleAveraging>
            <FastAxis>1</FastAxis>
            <SlowAxis>1</SlowAxis>
        </SpeckleAveraging>
        <Timestamp>1746702761</Timestamp>
        <ScanTime Unit="s">4.170000</ScanTime>
        <ScanPause Unit="s">0.000000</ScanPause>
        <RefractiveIndex>1.600000</RefractiveIndex>
        <ReferenceIntensity>0.728225</ReferenceIntensity>
        <Oversampling>0</Oversampling>
        <ApodizationType>EachBScan</ApodizationType>
        <ActualSizeOfApodization>25</ActualSizeOfApodization>
        <AcquisitionOrder>FrameByFrame</AcquisitionOrder>
        <AnalogInputActiveChannels />
    </Acquisition>
    <Processing>
        <FFTType>NFFT2</FFTType>
        <FFTOversampling>2.000000</FFTOversampling>
        <OffsetSubtraction>True</OffsetSubtraction>
        <DCSubtraction>True</DCSubtraction>
        <DCSubtractionAdvanced>True</DCSubtractionAdvanced>
        <OnlyWindowing>False</OnlyWindowing>
        <Apodization>True</Apodization>
        <ApoWindow>Tapered Cosine</ApoWindow>
        <ApoDataType>AcquiredInScan</ApoDataType>
        <UseExtendedAdjust>True</UseExtendedAdjust>
        <FilterDC>False</FilterDC>
        <UseScanForApodization>False</UseScanForApodization>
        <FullRangeOutput>False</FullRangeOutput>
        <UseDEFR>False</UseDEFR>
        <RemoveFixedPattern>False</RemoveFixedPattern>
        <DechirpApplied>True</DechirpApplied>
        <UndersampledFilter>False</UndersampledFilter>
        <DispersionCompensation>False</DispersionCompensation>
        <QuadraticDispersionCompensation>False</QuadraticDispersionCompensation>
        <QuadraticDispersionCompensationFactor>-3.000000</QuadraticDispersionCompensationFactor>
        <ImageFieldCorrection>True</ImageFieldCorrection>
        <AutoCorrCompensationUsed>False</AutoCorrCompensationUsed>
        <ElectronFloor>30000.000000</ElectronFloor>
        <DispersionPreset />
        <BScanCrossCorrelation>False</BScanCrossCorrelation>
        <InvertPhase>False</InvertPhase>
    </Processing>
    <PolarizationProcessing />
    <Instrument>
        <DevicePresetDescription Category="Speed/Sensitivity">Default (Medium sensitivity, 48 kHz)</DevicePresetDescription>
        <Model>TEL221</Model>
        <Series>Telesto</Series>
        <Serial>M01232798</Serial>
        <HardwareConfig>TEL221_V1</HardwareConfig>
        <Probe>Probe_Standard_OCTG_LSM03.ini</Probe>
        <SpectrometerElements>2048</SpectrometerElements>
        <BitDepth>12</BitDepth>
        <BytesPerPixel>2</BytesPerPixel>
        <RawDataIsSigned>False</RawDataIsSigned>
        <IsSweptSource>False</IsSweptSource>
        <CentralWavelength>1300.000000</CentralWavelength>
        <SourceBandwidth>243.165468</SourceBandwidth>
        <BinaryToElectronCountScaling>539.868164</BinaryToElectronCountScaling>
        <NumOfCameras>1</NumOfCameras>
        <SelectedCamera>0</SelectedCamera>
        <FullWellCapacity>2211300.000000</FullWellCapacity>
        <CameraLineRate>47841.000000</CameraLineRate>
        <AnalogInputNumOfChannels>4</AnalogInputNumOfChannels>
        <AnalogInputChannelNames>Galvo Feedback X,Galvo Feedback Y,Analog Input 1,Analog Input 2</AnalogInputChannelNames>
        <SpectrumDirection>Unknown</SpectrumDirection>
    </Instrument>
    <MetaInfo>
        <Comment />
        <CustomInfo />
        <AcquisitionMode>Mode3D</AcquisitionMode>
        <Study>GHL_pyapp_20250508T1112</Study>
        <ExperimentNumber>1</ExperimentNumber>
        <CompressionLevel>0</CompressionLevel>
        <ScanLineShown>True</ScanLineShown>
        <OriginalSoftwareVer>5.8.0</OriginalSoftwareVer>
        <LastModifiedSoftwareVer>5.8.0</LastModifiedSoftwareVer>
    </MetaInfo>
    <MarkerList />
</Ocity>

In [16]:
workbook.save(fname_excel)

In [62]:
cfg_oct_xml.Ocity.Instrument.DevicePresetDescription.etElem.text

'Default (Medium sensitivity, 48 kHz)'

In [17]:
octstudy.json_info_file['pos_leftmost_edge_center']

143.3