# Process and View Results From Multiple Longstrips

In [1]:
#%% imports
from pathlib import Path
# import json
# import configparser
import pprint
pp = pprint.PrettyPrinter(indent=4);
import time
import math
from collections import namedtuple

# # pip install slicerio
# import slicerio.server

# # packages for 3d
# #   # for OCT 3D stuff and using in jupyter
# #   - trame-jupyter-extension
# #   - trame
# #   - trame-vtk
# #   - trame-vuetify
# #   - ipywidgets

import matplotlib.pyplot as plt
import plotly.express as px

# interactive panels
import panel as pn
pn.extension('plotly');

import numpy as np
import pandas as pd
import addict

import cv2
import skimage
import scipy.signal
import networkx as nx

import pyvista as pv
from PIL import Image
import SimpleITK as sitk

# with vedo
#from vedo import dataurl, Volume, Text2D
import vedo
vedo.settings.default_backend = 'vtk'
#from vedo.applications import Slicer3DPlotter
import naatos_oct_tools.plotters.vedo_plotters as vedo_plotters
import naatos_oct_tools.plotters.sitk_plotters as sitk_plotters

import naatos_oct_tools.thorlabs_oct_file_reading
import naatos_oct_tools.oct_linear_scan_processing

In [2]:
# Magics to autoreload submodules when they are modified
%load_ext autoreload
%autoreload 2

In [3]:
#%% Test Record Excel
dftests = pd.read_excel(
    r'C:\Users\SimonGhionea\Global Health Labs, Inc\NAATOS Product Feasibility - TB V1 - General - Internal - Wax Valve\OCT\Test\OCT_wax_valve_test_record.xlsx',
    skiprows=1
)
dftests = dftests.iloc[:,1:]
dftests.rename(columns={'Unnamed: 19':'Notes'},inplace=True)
dftests

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Angle,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),File size (MB),Total size (GB),ProcessingNotes,Unnamed: 23
0,NaN,2025-03-26,GHL_pyapp_20250326T1258,oven aging test day 1,strip 7,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025-03-26,GHL_pyapp_20250326T1403,oven aging test day 1,strip 10,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2025-03-26,GHL_pyapp_20250326T1416,oven aging test day 1,strip 14,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2025-03-27,GHL_pyapp_20250327T1428,oven aging test day 2,strip 7,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2025-03-27,GHL_pyapp_20250327T1438,oven aging test day 2,strip 10,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,2025-03-27,GHL_pyapp_20250327T1450,oven aging test day 2,strip 14,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1.0,2025-04-14,GHL_pyapp_20250414T1541,0.3-0.324 mg/mm,0.302 02-13 10,0.302,1-sided magnetic,7.0,9.0,1.50000,...,NaN,105.1,-60.0,165.1,"Medium, 48kHz",2.0,425.000000,8.100000,NaN,Accidentually deleted
7,2.0,2025-04-14,GHL_pyapp_20250414T1610,0.3-0.324 mg/mm,0.308 02-26 11,0.308,1-sided magnetic,7.0,9.0,1.50000,...,NaN,105.1,-60.0,165.1,"Medium, 48kHz",2.0,425.000000,8.100000,NaN,NaN
8,3.0,2025-04-14,GHL_pyapp_20250414T1618,0.3-0.324 mg/mm,0.302 02-13 10,0.302,1-sided magnetic,7.0,9.0,1.50000,...,NaN,105.1,-60.0,165.1,"Medium, 48kHz",2.0,425.000000,8.100000,NaN,Repeat test 1
9,4.0,2025-04-14,GHL_pyapp_20250414T1636,0.3-0.324 mg/mm,ES0331 #26 0.320,0.320,1-sided magnetic,7.0,9.0,1.50000,...,NaN,104.8,-60.5,165.3,"Medium, 48kHz",2.0,425.000000,8.100000,NaN,NaN
10,5.0,2025-04-14,GHL_pyapp_20250414T1648,0.3-0.324 mg/mm,ES0325 #17 0.321,0.321,1-sided magnetic,7.0,9.0,1.50000,...,NaN,104.9,-60.1,165.0,"Medium, 48kHz",2.0,425.000000,8.100000,NaN,NaN
11,6.0,2025-04-15,GHL_pyapp_20250415T1120,0.3-0.324 mg/mm,ES0325 #17 0.321,0.321,1-sided magnetic,3.0,9.0,1.50000,...,NaN,104.9,-60.1,165.0,"Medium, 48kHz",2.0,183.000000,3.500000,NaN,Focus only on wax
12,7.0,2025-04-15,GHL_pyapp_20250415T1156,0.3-0.324 mg/mm,ES0325 #17 0.321,0.321,1-sided magnetic,7.0,8.0,1.50000,...,NaN,104.9,-60.1,165.0,"Medium, 48kHz",2.0,378.000000,7.900000,NaN,NaN
13,8.0,2025-04-15,GHL_pyapp_20250415T1257,<0.3 mg/mm,0.211 02-03 #10,0.211,1-sided magnetic,3.0,9.0,1.50000,...,NaN,105.0,-60.5,165.5,"Medium, 48kHz",2.0,183.000000,3.500000,NaN,NaN
14,9.0,2025-04-15,GHL_pyapp_20250415T1305,<0.3 mg/mm,0.286 02-13 21,0.286,1-sided magnetic,3.0,9.0,1.50000,...,NaN,105.0,-60.5,165.5,"Medium, 48kHz",2.0,183.000000,3.500000,NaN,NaN
15,10.0,2025-04-15,GHL_pyapp_20250415T1311,<0.3 mg/mm,0.286 02-13 21,0.286,1-sided magnetic,3.0,9.0,1.50000,...,NaN,105.0,-60.5,165.5,"Medium, 48kHz",2.0,183.000000,3.500000,NaN,"Same strip as test 9, but raise the z height a..."
16,11.0,2025-04-15,GHL_pyapp_20250415T1320,<0.3 mg/mm,0.139-02-25 3,0.139,1-sided magnetic,3.0,9.0,1.50000,...,NaN,105.0,-60.1,165.1,"Medium, 48kHz",2.0,183.000000,3.500000,NaN,NaN
17,12.0,2025-04-15,GHL_pyapp_20250415T1332,<0.3 mg/mm,0.221,0.221,1-sided magnetic,9.0,3.0,1.50000,...,NaN,104.9,-60.3,165.2,"Medium, 48kHz",2.0,183.000000,3.500000,NaN,"X, Y reversed in the software (bug?)"
18,13.0,2025-05-05,GHL_pyapp_20250505T1514,0.325-0.35,ES0408#12 0.329,0.329,Vacuum,9.0,3.5,1.50000,...,0.0,307.5,142.5,165.0,"Medium, 48kHz",2.0,213.000000,4.100000,NaN,NaN
19,14.0,2025-05-05,GHL_pyapp_20250505T1523,0.325-0.35,ES0408#11 0.336,0.336,Vacuum,9.0,3.5,1.50000,...,0.0,307.5,142.5,165.0,"Medium, 48kHz",2.0,213.000000,4.100000,NaN,NaN
20,15.0,2025-05-05,GHL_pyapp_20250505T1531,0.375-0.4,ES0331#10 0.387,0.387,Vacuum,9.0,3.5,1.50000,...,0.0,307.5,142.5,165.0,"Medium, 48kHz",2.0,213.000000,4.100000,NaN,NaN
21,16.0,2025-05-05,GHL_pyapp_20250505T1542,0.375-0.4,ES0331#4 0.384,0.384,Vacuum,9.0,3.5,1.50000,...,0.0,307.5,142.5,165.0,"Medium, 48kHz",2.0,213.000000,4.100000,NaN,NaN
22,17.0,2025-05-08,GHL_pyapp_20250508T1112,0.325-0.35,ES0408#17 0.327,0.327,Vacuum,9.0,3.5,2.39775,...,0.0,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218086,4.143631,"done,5",NUM_FOVS: remove +1
23,18.0,2025-05-08,GHL_pyapp_20250508T1128,0.325-0.35,ES0409#8 0.333,0.333,Vacuum,9.0,3.5,2.39775,...,0.0,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218077,4.143459,"done,5",NUM_FOVS: remove +1
24,19.0,2025-05-08,GHL_pyapp_20250508T1134,0.325-0.35,ES0410#18 0.333,0.333,Vacuum,9.0,3.5,2.39775,...,0.0,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218080,4.143517,"done,5",NUM_FOVS: remove +1
25,20.0,2025-05-08,GHL_pyapp_20250508T1143,0.375-0.4,ES0401#21 0.391,0.391,Vacuum,9.0,3.5,2.39775,...,0.0,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218082,4.143558,"done,5",NUM_FOVS: remove +1
26,21.0,2025-05-08,GHL_pyapp_20250508T1151,0.375-0.4,ES0403#33 0.392,0.392,Vacuum,9.0,3.5,2.39775,...,0.0,308.0,143.0,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218082,4.143550,"done,5",NUM_FOVS: remove +1
27,22.0,2025-05-08,GHL_pyapp_20250508T1158,0.375-0.4,ES0410#24 0.380,0.380,Vacuum,9.0,3.5,2.39775,...,0.0,308.0,143.0,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218091,4.143722,"done,5",NUM_FOVS: remove +1
28,23.0,2025-05-08,GHL_pyapp_20250508T1539,0.325-0.349mg/mm lrg bag,ES0410#20 0.338,0.338,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218090,4.143710,"done,5",Simon (my data fields from today to be populat...
29,24.0,2025-05-08,GHL_pyapp_20250508T1545,0.325-0.349mg/mm lrg bag,ES0408#3 0.334,0.334,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218089,4.143700,"done,5",Simon
30,25.0,2025-05-08,GHL_pyapp_20250508T1551,0.325-0.349mg/mm lrg bag,ES0408#13 0.341,0.341,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218086,4.143628,"done,5",Simon
31,26.0,2025-05-08,GHL_pyapp_20250508T1555,0.325-0.349mg/mm lrg bag,ES0408#30 0.349,0.349,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218091,4.143720,"done,5",Simon
32,27.0,2025-05-08,GHL_pyapp_20250508T1601,0.325-0.349mg/mm lrg bag,ES0415#29 0.349,0.349,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218099,4.143872,"done,5",Simon
33,28.0,2025-05-08,GHL_pyapp_20250508T1604,0.325-0.349mg/mm lrg bag,ES0414#4 0.343,0.343,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218093,4.143761,"done,5",Simon
34,29.0,2025-05-08,GHL_pyapp_20250508T1608,0.325-0.349mg/mm lrg bag,ES0410#9 0.340,0.340,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218074,4.143400,"done,5",Simon
35,30.0,2025-05-08,GHL_pyapp_20250508T1612,0.325-0.349mg/mm lrg bag,ES0415#25 0.340,0.340,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218063,4.143205,"done,5",Simon
36,31.0,2025-05-08,GHL_pyapp_20250508T1615,0.325-0.349mg/mm lrg bag,ES0415#17 0.349,0.349,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218067,4.143267,"done,5",Simon
37,32.0,2025-05-08,GHL_pyapp_20250508T1620,0.325-0.349mg/mm lrg bag,ES0415#5 0.328,0.328,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218070,4.143337,"done,5",Simon

In [5]:
#%% Filter The Tests To View
# dfmasks = [
#     (dftests['Test date']<'2025-03-28') & (dftests['Test date']>='2025-03-26'),
#     dftests['Test name'] != 'GHL_pyapp_20250326T1258'
# ]
# dfmasks = [
#     (dftests['Test date']<='2025-04-15') & (dftests['Test date']>='2025-04-14')
# ]
# dfmasks = [
#     (dftests['Test date']=='2025-05-05')
# ]
dfmasks = [
    (dftests['Test date']=='2025-05-08')
]

dffilt = dftests[np.all(dfmasks,axis=0)]
dffilt

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Angle,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),File size (MB),Total size (GB),ProcessingNotes,Unnamed: 23
22,17.0,2025-05-08,GHL_pyapp_20250508T1112,0.325-0.35,ES0408#17 0.327,0.327,Vacuum,9.0,3.5,2.39775,...,0.0,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218086,4.143631,"done,5",NUM_FOVS: remove +1
23,18.0,2025-05-08,GHL_pyapp_20250508T1128,0.325-0.35,ES0409#8 0.333,0.333,Vacuum,9.0,3.5,2.39775,...,0.0,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218077,4.143459,"done,5",NUM_FOVS: remove +1
24,19.0,2025-05-08,GHL_pyapp_20250508T1134,0.325-0.35,ES0410#18 0.333,0.333,Vacuum,9.0,3.5,2.39775,...,0.0,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218080,4.143517,"done,5",NUM_FOVS: remove +1
25,20.0,2025-05-08,GHL_pyapp_20250508T1143,0.375-0.4,ES0401#21 0.391,0.391,Vacuum,9.0,3.5,2.39775,...,0.0,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218082,4.143558,"done,5",NUM_FOVS: remove +1
26,21.0,2025-05-08,GHL_pyapp_20250508T1151,0.375-0.4,ES0403#33 0.392,0.392,Vacuum,9.0,3.5,2.39775,...,0.0,308.0,143.0,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218082,4.143550,"done,5",NUM_FOVS: remove +1
27,22.0,2025-05-08,GHL_pyapp_20250508T1158,0.375-0.4,ES0410#24 0.380,0.380,Vacuum,9.0,3.5,2.39775,...,0.0,308.0,143.0,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,0.218091,4.143722,"done,5",NUM_FOVS: remove +1
28,23.0,2025-05-08,GHL_pyapp_20250508T1539,0.325-0.349mg/mm lrg bag,ES0410#20 0.338,0.338,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218090,4.143710,"done,5",Simon (my data fields from today to be populat...
29,24.0,2025-05-08,GHL_pyapp_20250508T1545,0.325-0.349mg/mm lrg bag,ES0408#3 0.334,0.334,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218089,4.143700,"done,5",Simon
30,25.0,2025-05-08,GHL_pyapp_20250508T1551,0.325-0.349mg/mm lrg bag,ES0408#13 0.341,0.341,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218086,4.143628,"done,5",Simon
31,26.0,2025-05-08,GHL_pyapp_20250508T1555,0.325-0.349mg/mm lrg bag,ES0408#30 0.349,0.349,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218091,4.143720,"done,5",Simon
32,27.0,2025-05-08,GHL_pyapp_20250508T1601,0.325-0.349mg/mm lrg bag,ES0415#29 0.349,0.349,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218099,4.143872,"done,5",Simon
33,28.0,2025-05-08,GHL_pyapp_20250508T1604,0.325-0.349mg/mm lrg bag,ES0414#4 0.343,0.343,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218093,4.143761,"done,5",Simon
34,29.0,2025-05-08,GHL_pyapp_20250508T1608,0.325-0.349mg/mm lrg bag,ES0410#9 0.340,0.340,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218074,4.143400,"done,5",Simon
35,30.0,2025-05-08,GHL_pyapp_20250508T1612,0.325-0.349mg/mm lrg bag,ES0415#25 0.340,0.340,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218063,4.143205,"done,5",Simon
36,31.0,2025-05-08,GHL_pyapp_20250508T1615,0.325-0.349mg/mm lrg bag,ES0415#17 0.349,0.349,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218067,4.143267,"done,5",Simon
37,32.0,2025-05-08,GHL_pyapp_20250508T1620,0.325-0.349mg/mm lrg bag,ES0415#5 0.328,0.328,Vacuum,9.0,3.5,2.39775,...,0.0,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,0.218070,4.143337,"done,5",Simon

In [6]:
#%% Load OCT study information
octstudies = [];
#folder_octexport_root = Path(r'\\file.corp.ghlabs.org\Shared\Projects\NAATOS\V1\NAATOS_OCT_WORK\OCTExport')
folder_octexport_root = Path(r'D:\SGProjects\NAATOS\OCTlocal')

# Load list of data
for idx,record in dffilt.iterrows():
    octstudy = naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder(record['Test name'],folder_octexport_root);
    octstudies.append(octstudy);

STUDY: GHL_pyapp_20250508T1112
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1128
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1134
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1143
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1151
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1158
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1539
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1545
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1551
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1555
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1601
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1604
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1608
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1612
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1615
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250508T1620
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}

# Parse Through The OCTSTUDIES

In [7]:
#%% Load OCTSTUDY object, and start some processing on it
octstudies_to_run = [];
for idx,octstudy in enumerate(octstudies):
    octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder;
    print('~~~~~~~');
    print(octstudy.name);
    pp.pprint(octstudy.resultsCheck())
    doWeRunTheNotebook = any([v is False for k,v in octstudy.resultsCheck().items()])
    print('Run?',doWeRunTheNotebook)
    if(not doWeRunTheNotebook):
        octstudies_to_run.append(octstudy);

    print('~~~~~~~');
    print('We will analyze data for {:} octstudies.'.format(len(octstudies_to_run)))
    print([x.name for x in octstudies_to_run]);

~~~~~~~
GHL_pyapp_20250508T1112
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 1 octstudies.
['GHL_pyapp_20250508T1112']
~~~~~~~
GHL_pyapp_20250508T1128
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 2 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128']
~~~~~~~
GHL_pyapp_20250508T1134
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 3 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134']
~~~~~~~
GHL_pyapp_20250508T1143
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 4 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143']
~~~~~~~
GHL_pyapp_20250508T1151
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 5 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151']
~~~~~~~
GHL_pyapp_20250508T1158
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 6 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158']
~~~~~~~
GHL_pyapp_20250508T1539
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 7 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539']
~~~~~~~
GHL_pyapp_20250508T1545
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 8 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539', 'GHL_pyapp_20250508T1545']
~~~~~~~
GHL_pyapp_20250508T1551
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 9 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539', 'GHL_pyapp_20250508T1545', 'GHL_pyapp_20250508T1551']
~~~~~~~
GHL_pyapp_20250508T1555
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 10 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539', 'GHL_pyapp_20250508T1545', 'GHL_pyapp_20250508T1551', 'GHL_pyapp_20250508T1555']
~~~~~~~
GHL_pyapp_20250508T1601
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 11 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539', 'GHL_pyapp_20250508T1545', 'GHL_pyapp_20250508T1551', 'GHL_pyapp_20250508T1555', 'GHL_pyapp_20250508T1601']
~~~~~~~
GHL_pyapp_20250508T1604
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 12 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539', 'GHL_pyapp_20250508T1545', 'GHL_pyapp_20250508T1551', 'GHL_pyapp_20250508T1555', 'GHL_pyapp_20250508T1601', 'GHL_pyapp_20250508T1604']
~~~~~~~
GHL_pyapp_20250508T1608
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 13 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539', 'GHL_pyapp_20250508T1545', 'GHL_pyapp_20250508T1551', 'GHL_pyapp_20250508T1555', 'GHL_pyapp_20250508T1601', 'GHL_pyapp_20250508T1604', 'GHL_pyapp_20250508T1608']
~~~~~~~
GHL_pyapp_20250508T1612
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 14 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539', 'GHL_pyapp_20250508T1545', 'GHL_pyapp_20250508T1551', 'GHL_pyapp_20250508T1555', 'GHL_pyapp_20250508T1601', 'GHL_pyapp_20250508T1604', 'GHL_pyapp_20250508T1608', 'GHL_pyapp_20250508T1612']
~~~~~~~
GHL_pyapp_20250508T1615
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 15 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539', 'GHL_pyapp_20250508T1545', 'GHL_pyapp_20250508T1551', 'GHL_pyapp_20250508T1555', 'GHL_pyapp_20250508T1601', 'GHL_pyapp_20250508T1604', 'GHL_pyapp_20250508T1608', 'GHL_pyapp_20250508T1612', 'GHL_pyapp_20250508T1615']
~~~~~~~
GHL_pyapp_20250508T1620
{   'along_strip_data_extracted': [   '/dfstepA',
                                      '/dfstepB',
                                      '/dfstepC',
                                      '/dfstepD',
                                      '/dfstepE'],
    'exist_data_extracted': True,
    'figoutmp4_mazetest': True,
    'figoutmp4_stepA': True,
    'figoutmp4_stepB': True}
Run? False
~~~~~~~
We will analyze data for 16 octstudies.
['GHL_pyapp_20250508T1112', 'GHL_pyapp_20250508T1128', 'GHL_pyapp_20250508T1134', 'GHL_pyapp_20250508T1143', 'GHL_pyapp_20250508T1151', 'GHL_pyapp_20250508T1158', 'GHL_pyapp_20250508T1539', 'GHL_pyapp_20250508T1545', 'GHL_pyapp_20250508T1551', 'GHL_pyapp_20250508T1555', 'GHL_pyapp_20250508T1601', 'GHL_pyapp_20250508T1604', 'GHL_pyapp_20250508T1608', 'GHL_pyapp_20250508T1612', 'GHL_pyapp_20250508T1615', 'GHL_pyapp_20250508T1620']

# 1. From stored dataframes load summary data we care about

In [8]:
#octstudies_to_run = [octstudies_to_run[0]]
dfs = [];
for idx,octstudy in enumerate(octstudies_to_run):
    print(octstudy.name)

    octstudy.load_previously_saved_merged_volume();

    data_extracted = octstudy.load_data_extracted();
    dfstep = octstudy.load_data_extracted_along_strip();
    
    dfstep['octstudy'] = octstudy;

    dfs.append(dfstep)
    #data_extracted = 


    # Calculate Path From Top To Bottom
dfsteps = pd.concat(dfs,keys=[x.name for x in octstudies_to_run]);

GHL_pyapp_20250508T1112
Loading GHL_pyapp_20250508T1112_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1128
Loading GHL_pyapp_20250508T1128_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1134
Loading GHL_pyapp_20250508T1134_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1143
Loading GHL_pyapp_20250508T1143_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1151
Loading GHL_pyapp_20250508T1151_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1158
Loading GHL_pyapp_20250508T1158_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1539
Loading GHL_pyapp_20250508T1539_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1545
Loading GHL_pyapp_20250508T1545_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1551
Loading GHL_pyapp_20250508T1551_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1555
Loading GHL_pyapp_20250508T1555_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1601
Loading GHL_pyapp_20250508T1601_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1604
Loading GHL_pyapp_20250508T1604_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1608
Loading GHL_pyapp_20250508T1608_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1612
Loading GHL_pyapp_20250508T1612_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1615
Loading GHL_pyapp_20250508T1615_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE
GHL_pyapp_20250508T1620
Loading GHL_pyapp_20250508T1620_STACKED_RESCALED_30to60_uint8.vtk
Loading /dfstepA
Loading /dfstepB
Loading /dfstepC
Loading /dfstepD
Loading /dfstepE

In [9]:
dfsteps

                               pixel_depth_strip_top_sum_threshold  \
                        slice
GHL_pyapp_20250508T1112 5                                    57.76
                        10                                   56.80
                        15                                   59.52
                        20                                   56.60
                        25                                   58.08
...                                                            ...
GHL_pyapp_20250508T1620 8250                                 53.52
                        8255                                 53.92
                        8260                                 53.64
                        8265                                 53.28
                        8270                                 54.10

                               pixel_depth_strip_top  pixel_depth_strip_bot  \
                        slice
GHL_pyapp_20250508T1112 5                        181                    247
                        10                       182                    246
                        15                       183                    244
                        20                       184                    244
                        25                       184                    243
...                                              ...                    ...
GHL_pyapp_20250508T1620 8250                     268                    331
                        8255                     266                    329
                        8260                     263                    329
                        8265                     260                    327
                        8270                     257                    322

                               pixel_depth_wax_center  \
                        slice
GHL_pyapp_20250508T1112 5                         222
                        10                        223
                        15                        226
                        20                        231
                        25                        223
...                                               ...
GHL_pyapp_20250508T1620 8250                      313
                        8255                      300
                        8260                      302
                        8265                      303
                        8270                      303

                                               px_wax_transverse_edges  \
                        slice
GHL_pyapp_20250508T1112 5      (56.33712121212121, 105.00769230769231)
                        10     (56.755319148936174, 105.3936170212766)
                        15      (56.82631578947368, 103.9396551724138)
                        20     (55.68604651162791, 102.38636363636364)
                        25     (53.572463768115945, 102.2843137254902)
...                                                                ...
GHL_pyapp_20250508T1620 8250   (75.21428571428571, 112.86585365853658)
                        8255    (75.59433962264151, 111.8030303030303)
                        8260            (74.046875, 108.2872340425532)
                        8265   (73.17785234899328, 105.88461538461539)
                        8270   (73.25882352941177, 107.01470588235294)

                              wax_top_seed_candidate_px  \
                        slice
GHL_pyapp_20250508T1112 5                     (190, 80)
                        10                    (195, 80)
                        15                    (202, 79)
                        20                    (203, 78)
                        25                    (206, 77)
...                                                 ...
GHL_pyapp_20250508T1620 8250                  (270, 94)
                        8255                  (266, 93)
                        8260                  (266, 91)
                        8265                  (260, 89)
                        8270                  (261, 90)

                                                                            pksA  \
                        slice
GHL_pyapp_20250508T1112 5      ([11, 91, 163], {'prominences': [3602.0, 714.0...
                        10     ([15, 60, 90, 124, 162], {'prominences': [4589...
                        15     ([19, 59, 107, 166], {'prominences': [6548.0, ...
                        20     ([19, 58, 110, 166], {'prominences': [6682.0, ...
                        25     ([26, 61, 107, 166], {'prominences': [6172.0, ...
...                                                                          ...
GHL_pyapp_20250508T1620 8250   ([4, 59, 126, 163], {'prominences': [945.0, 81...
                        8255   ([2, 54, 130, 163], {'prominences': [692.0, 86...
                        8260   ([3, 54, 134, 166], {'prominences': [765.0, 58...
                        8265   ([4, 43, 172, 273], {'prominences': [1098.0, 6...
                        8270   ([5, 35, 74], {'prominences': [1626.0, 160.0, ...

                                                                            pksB  \
                        slice
GHL_pyapp_20250508T1112 5      ([12, 81, 169, 233], {'prominences': [1629.0, ...
                        10     ([15, 82, 163, 233], {'prominences': [3734.0, ...
                        15     ([18, 107, 168, 228, 401], {'prominences': [62...
                        20     ([20, 107, 167, 214], {'prominences': [7049.0,...
                        25     ([25, 106, 169, 205, 385], {'prominences': [83...
...                                                                          ...
GHL_pyapp_20250508T1620 8250   ([4, 130, 160, 233], {'prominences': [338.0, 1...
                        8255   ([3, 131, 162, 238, 307], {'prominences': [221...
                        8260   ([5, 136, 171, 243], {'prominences': [404.0, 1...
                        8265   ([4, 178, 245], {'prominences': [217.0, 2567.0...
                        8270   ([5, 74, 188], {'prominences': [537.0, 260.0, ...

                                                                           pksB2  \
                        slice
GHL_pyapp_20250508T1112 5      ([12, 182, 252], {'peak_heights': [3997.591303...
                        10     ([15, 167, 233], {'peak_heights': [3495.389997...
                        15     ([19, 107, 168, 229], {'peak_heights': [3634.7...
                        20     ([20, 107, 168, 215], {'peak_heights': [2920.4...
                        25     ([25, 169, 205], {'peak_heights': [3135.616720...
...                                                                          ...
GHL_pyapp_20250508T1620 8250   ([4, 162, 234], {'peak_heights': [3027.4644441...
                        8255   ([4, 163, 238], {'peak_heights': [2924.7293722...
                        8260   ([5, 171, 243], {'peak_heights': [2749.2221745...
                        8265   ([5, 180, 246], {'peak_heights': [2591.3729039...
                        8270   ([7, 189], {'peak_heights': [2345.325046062285...

                               wax_roi_valve_bottom  \
                        slice
GHL_pyapp_20250508T1112 5                       252
                        10                      233
                        15                      229
                        20                      215
                        25                      169
...                                             ...
GHL_pyapp_20250508T1620 8250                    162
                        8255                    163
                        8260                    171
                        8265                    180
                        8270                    189

                                                            testseg_otsu_regions  \
                        slice
GHL_pyapp_20250508T1112 5      [[3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
                        10     [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,...
                        15     [[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 4, 4,...
                        20     [[0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3,...
                        25     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 3, 3,...
...                                                                          ...
GHL_pyapp_20250508T1620 8250   [[3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
                        8255   [[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
                        8260   [[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
                        8265   [[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
                        8270   [[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...

                              testseg_otsu_thresholds  \
                        slice
GHL_pyapp_20250508T1112 5          [59, 93, 135, 196]
                        10        [64, 102, 149, 204]
                        15        [64, 101, 141, 191]
                        20         [55, 86, 123, 177]
                        25         [56, 91, 129, 183]
...                                               ...
GHL_pyapp_20250508T1620 8250      [57, 101, 152, 208]
                        8255      [61, 103, 152, 206]
                        8260       [55, 92, 139, 195]
                        8265       [56, 95, 139, 195]
                        8270       [56, 93, 142, 202]

                               final_wax_bot_subset_px  \
                        slice
GHL_pyapp_20250508T1112 5                          167
                        10                         168
                        15                         168
                        20                         169
                        25                         177
...                                                ...
GHL_pyapp_20250508T1620 8250                       162
                        8255                       163
                        8260                       171
                        8265                       180
                        8270                       188

                                                       seg_thresh_sauvola_cutoff  \
                        slice
GHL_pyapp_20250508T1112 5      [[False, False, False, False, False, False, Fa...
                        10     [[False, False, False, False, False, False, Fa...
                        15     [[False, False, False, False, False, False, Fa...
                        20     [[False, False, False, False, False, False, Fa...
                        25     [[False, False, False, False, False, False, Fa...
...                                                                          ...
GHL_pyapp_20250508T1620 8250   [[False, False, False, False, False, False, Fa...
                        8255   [[False, False, False, False, False, False, Fa...
                        8260   [[False, False, False, False, False, False, Fa...
                        8265   [[True, True, False, False, False, False, Fals...
                        8270   [[False, False, False, False, False, False, Fa...

                                 area  area_filled  area_convex  num_paths  \
                        slice
GHL_pyapp_20250508T1112 5      4535.0       4679.0       5911.0          0
                        10     4969.0       5164.0       6318.0          0
                        15     4838.0       4972.0       6146.0          0
                        20     5005.0       5029.0       6316.0          0
                        25     5255.0       5296.0       7012.0          0
...                               ...          ...          ...        ...
GHL_pyapp_20250508T1620 8250   4260.0       4260.0       5354.0          0
                        8255   4053.0       4066.0       5347.0          0
                        8260   4118.0       4427.0       5192.0          0
                        8265   3695.0       3794.0       5307.0          0
                        8270   3860.0       3914.0       4960.0          0

                                                                        octstudy
                        slice
GHL_pyapp_20250508T1112 5      <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        10     <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        15     <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        20     <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        25     <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
...                                                                          ...
GHL_pyapp_20250508T1620 8250   <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        8255   <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        8260   <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        8265   <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...
                        8270   <OCT_Study_Folder Object>\nGHL_pyapp_20250508T...

[26352 rows x 19 columns]

In [10]:
import gc
gc.collect()

40

# handle the source image

In [11]:
def getSitkImage(octstudy_with_loaded_vdvol):
    # Test getting SITK image
    # Get ITK image without requiring new memory
    import itk
    import vtk

    # function to go from itk image to simpleitk image
    def itkToSimpleITK(itk_image):
        new_sitk_image = sitk.GetImageFromArray(itk.GetArrayViewFromImage(itk_image),isVector=itk_image.GetNumberOfComponentsPerPixel()>1);
        new_sitk_image.SetOrigin(tuple(itk_image.GetOrigin()))
        new_sitk_image.SetSpacing(tuple(itk_image.GetSpacing()))
        new_sitk_image.SetDirection(itk.GetArrayFromMatrix(itk_image.GetDirection()).flatten()) 
        return new_sitk_image;

    print('Get volume for',octstudy_with_loaded_vdvol.name)

    # create simpleitk 3dimage, directly from the previously-loaded vtk 3dimage
    simgmerged = itkToSimpleITK( itk.image_from_vtk_image(octstudy_with_loaded_vdvol.vdvol.dataset) );



    # itk_image
    #print(itk_image)
    slicer_1 = slice( data_extracted['auto_bounds']['topdown_edge_left_px3']  ,  data_extracted['auto_bounds']['topdown_edge_right_px3']  )
    #print(' slicer_dim_0',slicer_0)
    print(' slicer_dim_1',slicer_1)
    #simgmerged.GetSize()
    return simgmerged,{'slicer_1':slicer_1};

simgmerged,voldata = getSitkImage(octstudy);
slicer_1 = voldata['slicer_1'];

Get volume for GHL_pyapp_20250508T1620
 slicer_dim_1 slice(195, 8468, None)

In [12]:
print( simgmerged[:,slicer_1,:] )

Image (000001DBF30ACC20)
  RTTI typeinfo:   class itk::Image<unsigned char,3>
  Reference Count: 1
  Modified Time: 1705
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 1692
  UpdateMTime: 1704
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [690, 8273, 175]
  BufferedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [690, 8273, 175]
  RequestedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [690, 8273, 175]
  Spacing: [0.003475, 0.02, 0.02]
  Origin: [0, 3.9, 0]
  Direction:
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix:
0.003475 0 0
0 0.02 0
0 0 0.02

  PointToIndexMatrix:
287.77 0 0
0 50 0
0 0 50

  Inverse Direction:
1 0 0
0 1 0
0 0 1

  PixelContainer:
    ImportImageContainer (000001E091BEEE20)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,unsigned char>
      Reference Count: 1
      Modified Time: 1701
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 000001E265BCA040
      Container manages memory: true
      Size: 998964750
      Capacity: 998964750

In [13]:
slab_thickness = 10; # px, this was used in the bulk analysis
slice_position_along_strip_px = 4000;
slab_slicer = slice(slice_position_along_strip_px-slab_thickness//2,slice_position_along_strip_px+slab_thickness//2);
simg_slab_img = (simgmerged[:,slicer_1,:])[:,slab_slicer,:]

# 3. Plot Of Values Along Strip

In [13]:
slice_centers = dfsteps.index;

In [14]:
simgmerged_summed = sitk.SumProjection(simgmerged[:,slicer_1,:],projectionDimension=0);

In [15]:
print(simgmerged_summed)

Image (000001DBF30ACEF0)
  RTTI typeinfo:   class itk::Image<double,3>
  Reference Count: 1
  Modified Time: 1771
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 1760
  UpdateMTime: 1770
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [1, 8273, 175]
  BufferedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [1, 8273, 175]
  RequestedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [1, 8273, 175]
  Spacing: [2.39775, 0.02, 0.02]
  Origin: [7.46251e+06, 3.9, 0]
  Direction:
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix:
2.39775 0 0
0 0.02 0
0 0 0.02

  PointToIndexMatrix:
0.417058 0 0
0 50 0
0 0 50

  Inverse Direction:
1 0 0
0 1 0
0 0 1

  PixelContainer:
    ImportImageContainer (000001DBE91194B0)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,double>
      Reference Count: 1
      Modified Time: 1768
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 000001E132F21040
      Container manages memory: true
      Size: 1447775
      Capacity: 1447775

In [16]:
ndaimg = sitk.GetArrayFromImage(sitk.RescaleIntensity(simgmerged_summed,0,255)); # numpy array

In [17]:
ndaimg

array([[[63.85712218],
        [62.47529728],
        [64.93551966],
        ...,
        [60.90075495],
        [89.5397937 ],
        [59.68909543]],

       [[66.33374605],
        [68.6586562 ],
        [69.12404827],
        ...,
        [59.76700247],
        [56.22018186],
        [63.79561662]],

       [[65.99956584],
        [73.72466413],
        [64.4270737 ],
        ...,
        [69.1199479 ],
        [61.88279372],
        [65.44396562]],

       ...,

       [[51.98244881],
        [54.24175303],
        [53.68615281],
        ...,
        [93.67911786],
        [45.64532598],
        [15.17957211]],

       [[59.24010484],
        [51.31203821],
        [54.27660618],
        ...,
        [53.6451491 ],
        [32.01979434],
        [ 4.51450808]],

       [[68.36137933],
        [60.47636659],
        [54.18434784],
        ...,
        [54.11054117],
        [49.83385459],
        [ 2.4294696 ]]])

In [18]:
#ndaimg = sitk.GetArrayViewFromImage(simgmerged_summed); # numpy array
from PIL import Image
import base64
from io import BytesIO
pil_img = Image.fromarray(ndaimg[:,:,0]) # PIL image object

In [ ]:

ndaimg = sitk.GetArrayViewFromImage(simgmerged_summed); # numpy array
from PIL import Image
import base64
from io import BytesIO
pil_img = Image.fromarray(ndaimg[:,:,0]) # PIL image object

In [ ]:
pil_img.show()

In [20]:
studyname = dfsteps.index.get_level_values(0).unique().tolist()[1];
octstudy = dfsteps.loc[studyname].iloc[0]['octstudy']

simgmerged,voldata = getSitkImage(octstudy);
slicer_1 = voldata['slicer_1'];
df = dfsteps.loc[studyname,:]

Get volume for GHL_pyapp_20250508T1128
 slicer_dim_1 slice(195, 8468, None)

In [63]:
# Make Detailed Metrics Plots Of 1-Device
import plotly.graph_objects as go
from plotly.subplots import make_subplots

nrows = 5
fig = make_subplots(rows=nrows,shared_xaxes=True,vertical_spacing=0.02, )

slice_centers = df.index;

myrow = 1;
if True:
    # make image
    legendgroup = 'image';

    # use previously created simpleitk merged image filter
    #ndaimg = sitk.GetArrayViewFromImage(simgmerged_summed); # numpy array
    ndaimg = sitk.GetArrayFromImage(sitk.RescaleIntensity(simgmerged_summed,0,255)); # numpy array
    print(ndaimg.shape)
    from PIL import Image
    import base64
    from io import BytesIO
    pil_img = Image.fromarray(ndaimg[:,:,0]) # PIL image object
    pil_img = pil_img.convert("L"); # grayscale image convert, from float
    prefix = "data:image/png;base64,"
    with BytesIO() as stream:
        pil_img.save(stream, format="png")
        base64_string = prefix + base64.b64encode(stream.getvalue()).decode("utf-8")

    fig.add_trace(
        go.Image(
            source=base64_string,
            #cmap='jet',
        ),
        row=myrow,col=1,
    )

legendgroup = 'distances';
myrow+=1;
# Wax Thickness
wax_top = df.loc[slice_centers]['wax_top_seed_candidate_px'].apply(lambda x: x[0]);
#wax_top = dfstepA.loc[final_wax_centers]['pixel_depth_strip_top']
wax_bot = df.loc[slice_centers]['pixel_depth_strip_top']+df.loc[slice_centers]['final_wax_bot_subset_px']
wax_thickness = wax_bot-wax_top
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = wax_thickness,
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_thickness1',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
#fig.update_yaxes(title='Wax Valve Width (pixels)',col=1);


# Wax Thickness
wax_top = df.loc[slice_centers]['wax_top_seed_candidate_px'].apply(lambda x: x[0]);
#wax_top = dfstepA.loc[final_wax_centers]['pixel_depth_strip_top']
wax_bot = df.loc[slice_centers]['pixel_depth_strip_top']+df.loc[slice_centers]['final_wax_bot_subset_px']
wax_thickness = wax_bot-df.loc[slice_centers]['pixel_depth_strip_top']
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = wax_thickness,
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_thickness2',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['px_wax_transverse_edges'].apply(lambda x: np.diff(x)[0]),
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_width_px',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = wax_top,
        #type = 'heatmap',
        #colorscale = 'jet'
        name='wax_top',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)




legendgroup = 'areas';
myrow+=1;
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled']-df['area'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_holes',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_filled',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_convex',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)


legendgroup = 'ratios';
myrow+=1;
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area']/df['area_filled'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_to_areafilled_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area']/df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_area_to_areaconvex_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['area_filled']/df['area_convex'],
        #type = 'heatmap',
        #colorscale = 'jet'
        name='seg_areafilled_to_areaconvex_ratio',
        legendgroup=legendgroup
    ),
    row=myrow,col=1,
)

legendgroup = 'counts';
myrow+=1;
fig.add_trace(
    go.Scatter(
        x = slice_centers,
        y = df['num_paths'],
        name='crossovers_px_paths',
        legendgroup=legendgroup,
    ),
    row=myrow,col=1,
)
fig.update_yaxes(row=myrow,type='log')

# setup legends per row
for i, yaxis in enumerate(fig.select_yaxes(col=1), 1):
    legend_name = f"legend{i}"
    fig.update_layout({legend_name: dict(y=yaxis.domain[1], yanchor="top")}, showlegend=True)
    fig.update_traces(row=i, legend=legend_name)

fig.update_traces(xaxis='x{:}'.format(nrows))
fig.update_yaxes(title='pixels',row=1);
fig.update_yaxes(title='pixels^2',row=2);
fig.update_yaxes(title='ratios',row=3);
fig.update_yaxes(title='counts',row=4);
fig.update_xaxes(title='distance along strip (px)',row=nrows,col=1);
fig.update_layout(hovermode='x unified',hoversubplots="axis",spikedistance=-1);
#fig = px.imshow(sum_wax_strip_along_length[:,0:]);

fig.show(renderer='browser')
#fig

(175, 8273, 1)

In [ ]:
fig.update_yaxes(row=1,scaleanchor=None)

In [53]:
fig.layout

Layout({
    'hovermode': 'x unified',
    'hoversubplots': 'axis',
    'legend': {'y': 1.0, 'yanchor': 'top'},
    'legend2': {'y': 0.796, 'yanchor': 'top'},
    'legend3': {'y': 0.592, 'yanchor': 'top'},
    'legend4': {'y': 0.388, 'yanchor': 'top'},
    'legend5': {'y': 0.184, 'yanchor': 'top'},
    'showlegend': True,
    'spikedistance': -1,
    'template': '...',
    'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'matches': 'x5', 'showticklabels': False},
    'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0], 'matches': 'x5', 'showticklabels': False},
    'xaxis3': {'anchor': 'y3', 'domain': [0.0, 1.0], 'matches': 'x5', 'showticklabels': False},
    'xaxis4': {'anchor': 'y4', 'domain': [0.0, 1.0], 'matches': 'x5', 'showticklabels': False},
    'xaxis5': {'anchor': 'y5', 'domain': [0.0, 1.0], 'title': {'text': 'distance along strip (px)'}},
    'yaxis': {'anchor': 'x', 'domain': [0.816, 1.0], 'title': {'text': 'pixels'}},
    'yaxis2': {'anchor': 'x2', 'domain': [0.6120000000000001, 0.796], 'title': {'text': 'pixels^2'}},
    'yaxis3': {'anchor': 'x3', 'domain': [0.408, 0.592], 'title': {'text': 'ratios'}},
    'yaxis4': {'anchor': 'x4', 'domain': [0.204, 0.388], 'title': {'text': 'counts'}},
    'yaxis5': {'anchor': 'x5', 'domain': [0.0, 0.184], 'type': 'log'}
})

In [62]:
fig.layout.yaxis5

layout.YAxis({
    'anchor': 'x5', 'domain': [0.0, 0.184], 'type': 'log'
})