# Process Multiple Long Strips

In [1]:
#%% imports
from pathlib import Path
# import json
# import configparser
import pprint
pp = pprint.PrettyPrinter(indent=4);
import time
import math
from collections import namedtuple

# # pip install slicerio
# import slicerio.server

# # packages for 3d
# #   # for OCT 3D stuff and using in jupyter
# #   - trame-jupyter-extension
# #   - trame
# #   - trame-vtk
# #   - trame-vuetify
# #   - ipywidgets

import matplotlib.pyplot as plt
import plotly.express as px

# interactive panels
import panel as pn
pn.extension('plotly');

import numpy as np
import pandas as pd
import addict

import cv2
import skimage
import scipy.signal

import pyvista as pv
from PIL import Image
import SimpleITK as sitk

# with vedo
#from vedo import dataurl, Volume, Text2D
import vedo
vedo.settings.default_backend = 'vtk'
#from vedo.applications import Slicer3DPlotter
import naatos_oct_tools.plotters.vedo_plotters as vedo_plotters
import naatos_oct_tools.plotters.sitk_plotters as sitk_plotters

import naatos_oct_tools.thorlabs_oct_file_reading
import naatos_oct_tools.oct_linear_scan_processing

import papermill

In [2]:
# Magics to autoreload submodules when they are modified
%load_ext autoreload
%autoreload 2

In [3]:
#%% Test Record Excel
dftests = pd.read_excel(
    r'C:\Users\SimonGhionea\Global Health Labs, Inc\NAATOS Product Feasibility - TB V1 - General - Internal - Wax Valve\OCT\Test\OCT_wax_valve_test_record.xlsx',
    skiprows=1
)
dftests = dftests.iloc[:,1:]
dftests.rename(columns={'Unnamed: 19':'Notes'},inplace=True)
dftests

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Unnamed: 24
0,NaN,2025-03-26,GHL_pyapp_20250326T1258,oven aging test day 1,strip 7,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025-03-26,GHL_pyapp_20250326T1403,oven aging test day 1,strip 10,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2025-03-26,GHL_pyapp_20250326T1416,oven aging test day 1,strip 14,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2025-03-27,GHL_pyapp_20250327T1428,oven aging test day 2,strip 7,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2025-03-27,GHL_pyapp_20250327T1438,oven aging test day 2,strip 10,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,2025-03-27,GHL_pyapp_20250327T1450,oven aging test day 2,strip 14,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1.0,2025-04-14,GHL_pyapp_20250414T1541,0.3-0.324 mg/mm,0.302 02-13 10,0.302,1-sided magnetic,7.0,9.0,1.50000,...,105.1,-60.0,165.1,"Medium, 48kHz",2.0,1.6,425.000000,8.100000,NaN,Accidentually deleted
7,2.0,2025-04-14,GHL_pyapp_20250414T1610,0.3-0.324 mg/mm,0.308 02-26 11,0.308,1-sided magnetic,7.0,9.0,1.50000,...,105.1,-60.0,165.1,"Medium, 48kHz",2.0,1.6,425.000000,8.100000,NaN,NaN
8,3.0,2025-04-14,GHL_pyapp_20250414T1618,0.3-0.324 mg/mm,0.302 02-13 10,0.302,1-sided magnetic,7.0,9.0,1.50000,...,105.1,-60.0,165.1,"Medium, 48kHz",2.0,1.6,425.000000,8.100000,NaN,Repeat test 1
9,4.0,2025-04-14,GHL_pyapp_20250414T1636,0.3-0.324 mg/mm,ES0331 #26 0.320,0.320,1-sided magnetic,7.0,9.0,1.50000,...,104.8,-60.5,165.3,"Medium, 48kHz",2.0,1.6,425.000000,8.100000,NaN,NaN
10,5.0,2025-04-14,GHL_pyapp_20250414T1648,0.3-0.324 mg/mm,ES0325 #17 0.321,0.321,1-sided magnetic,7.0,9.0,1.50000,...,104.9,-60.1,165.0,"Medium, 48kHz",2.0,1.6,425.000000,8.100000,NaN,NaN
11,6.0,2025-04-15,GHL_pyapp_20250415T1120,0.3-0.324 mg/mm,ES0325 #17 0.321,0.321,1-sided magnetic,3.0,9.0,1.50000,...,104.9,-60.1,165.0,"Medium, 48kHz",2.0,1.6,183.000000,3.500000,NaN,Focus only on wax
12,7.0,2025-04-15,GHL_pyapp_20250415T1156,0.3-0.324 mg/mm,ES0325 #17 0.321,0.321,1-sided magnetic,7.0,8.0,1.50000,...,104.9,-60.1,165.0,"Medium, 48kHz",2.0,1.6,378.000000,7.900000,NaN,NaN
13,8.0,2025-04-15,GHL_pyapp_20250415T1257,<0.3 mg/mm,0.211 02-03 #10,0.211,1-sided magnetic,3.0,9.0,1.50000,...,105.0,-60.5,165.5,"Medium, 48kHz",2.0,1.6,183.000000,3.500000,NaN,NaN
14,9.0,2025-04-15,GHL_pyapp_20250415T1305,<0.3 mg/mm,0.286 02-13 21,0.286,1-sided magnetic,3.0,9.0,1.50000,...,105.0,-60.5,165.5,"Medium, 48kHz",2.0,1.6,183.000000,3.500000,NaN,NaN
15,10.0,2025-04-15,GHL_pyapp_20250415T1311,<0.3 mg/mm,0.286 02-13 21,0.286,1-sided magnetic,3.0,9.0,1.50000,...,105.0,-60.5,165.5,"Medium, 48kHz",2.0,1.6,183.000000,3.500000,NaN,"Same strip as test 9, but raise the z height a..."
16,11.0,2025-04-15,GHL_pyapp_20250415T1320,<0.3 mg/mm,0.139-02-25 3,0.139,1-sided magnetic,3.0,9.0,1.50000,...,105.0,-60.1,165.1,"Medium, 48kHz",2.0,1.6,183.000000,3.500000,NaN,NaN
17,12.0,2025-04-15,GHL_pyapp_20250415T1332,<0.3 mg/mm,0.221,0.221,1-sided magnetic,9.0,3.0,1.50000,...,104.9,-60.3,165.2,"Medium, 48kHz",2.0,1.6,183.000000,3.500000,NaN,"X, Y reversed in the software (bug?)"
18,13.0,2025-05-05,GHL_pyapp_20250505T1514,0.325-0.35,ES0408#12 0.329,0.329,Vacuum,9.0,3.5,1.50000,...,307.5,142.5,165.0,"Medium, 48kHz",2.0,1.6,213.000000,4.100000,NaN,NaN
19,14.0,2025-05-05,GHL_pyapp_20250505T1523,0.325-0.35,ES0408#11 0.336,0.336,Vacuum,9.0,3.5,1.50000,...,307.5,142.5,165.0,"Medium, 48kHz",2.0,1.6,213.000000,4.100000,NaN,NaN
20,15.0,2025-05-05,GHL_pyapp_20250505T1531,0.375-0.4,ES0331#10 0.387,0.387,Vacuum,9.0,3.5,1.50000,...,307.5,142.5,165.0,"Medium, 48kHz",2.0,1.6,213.000000,4.100000,NaN,NaN
21,16.0,2025-05-05,GHL_pyapp_20250505T1542,0.375-0.4,ES0331#4 0.384,0.384,Vacuum,9.0,3.5,1.50000,...,307.5,142.5,165.0,"Medium, 48kHz",2.0,1.6,213.000000,4.100000,NaN,NaN
22,17.0,2025-05-08,GHL_pyapp_20250508T1112,0.325-0.35,ES0408#17 0.327,0.327,Vacuum,9.0,3.5,2.39775,...,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218086,4.143631,"done,5",NUM_FOVS: remove +1
23,18.0,2025-05-08,GHL_pyapp_20250508T1128,0.325-0.35,ES0409#8 0.333,0.333,Vacuum,9.0,3.5,2.39775,...,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218077,4.143459,"done,5",NUM_FOVS: remove +1
24,19.0,2025-05-08,GHL_pyapp_20250508T1134,0.325-0.35,ES0410#18 0.333,0.333,Vacuum,9.0,3.5,2.39775,...,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218080,4.143517,"done,5",NUM_FOVS: remove +1
25,20.0,2025-05-08,GHL_pyapp_20250508T1143,0.375-0.4,ES0401#21 0.391,0.391,Vacuum,9.0,3.5,2.39775,...,307.5,142.5,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218082,4.143558,"done,5",NUM_FOVS: remove +1
26,21.0,2025-05-08,GHL_pyapp_20250508T1151,0.375-0.4,ES0403#33 0.392,0.392,Vacuum,9.0,3.5,2.39775,...,308.0,143.0,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218082,4.143550,"done,5",NUM_FOVS: remove +1
27,22.0,2025-05-08,GHL_pyapp_20250508T1158,0.375-0.4,ES0410#24 0.380,0.380,Vacuum,9.0,3.5,2.39775,...,308.0,143.0,165.0,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218091,4.143722,"done,5",NUM_FOVS: remove +1
28,23.0,2025-05-08,GHL_pyapp_20250508T1539,0.325-0.349mg/mm lrg bag blu,ES0410#20 0.338,0.338,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218090,4.143710,"done,5",Simon (my data fields from today to be populat...
29,24.0,2025-05-08,GHL_pyapp_20250508T1545,0.325-0.349mg/mm lrg bag blu,ES0408#3 0.334,0.334,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218089,4.143700,"done,5",Simon
30,25.0,2025-05-08,GHL_pyapp_20250508T1551,0.325-0.349mg/mm lrg bag blu,ES0408#13 0.341,0.341,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218086,4.143628,"done,5",Simon
31,26.0,2025-05-08,GHL_pyapp_20250508T1555,0.325-0.349mg/mm lrg bag blu,ES0408#30 0.349,0.349,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218091,4.143720,"done,5",Simon
32,27.0,2025-05-08,GHL_pyapp_20250508T1601,0.325-0.349mg/mm lrg bag blu,ES0415#29 0.349,0.349,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218099,4.143872,"done,5",Simon
33,28.0,2025-05-08,GHL_pyapp_20250508T1604,0.325-0.349mg/mm lrg bag blu,ES0414#4 0.343,0.343,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218093,4.143761,"done,5",Simon
34,29.0,2025-05-08,GHL_pyapp_20250508T1608,0.325-0.349mg/mm lrg bag blu,ES0410#9 0.340,0.340,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218074,4.143400,"done,5",Simon
35,30.0,2025-05-08,GHL_pyapp_20250508T1612,0.325-0.349mg/mm lrg bag blu,ES0415#25 0.340,0.340,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218063,4.143205,"done,5",Simon
36,31.0,2025-05-08,GHL_pyapp_20250508T1615,0.325-0.349mg/mm lrg bag blu,ES0415#17 0.349,0.349,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218067,4.143267,"done,5",Simon
37,32.0,2025-05-08,GHL_pyapp_20250508T1620,0.325-0.349mg/mm lrg bag blu,ES0415#5 0.328,0.328,Vacuum,9.0,3.5,2.39775,...,309.0,143.3,165.7,"Default (Medium sensitivity, 48 kHz)",2.0,1.6,0.218070,4.143337,"done,5",Simon
38,33.0,2025-05-12,GHL_pyapp_20250512T0947,0.350-0.374mg/mm lrg bag blu,ES0414#7 0.367,0.367,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,34.0,2025-05-12,GHL_pyapp_20250512T0951,0.350-0.374mg/mm lrg bag blu,ES0414#5 0.352,0.352,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,35.0,2025-05-12,GHL_pyapp_20250512T0955,0.350-0.374mg/mm lrg bag blu,ES0415#8 0.351,0.351,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,36.0,2025-05-12,GHL_pyapp_20250512T0959,0.350-0.374mg/mm lrg bag blu,ES0408#16 0.372,0.372,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,37.0,2025-05-12,GHL_pyapp_20250512T1002,0.350-0.374mg/mm lrg bag blu,ES0409#7 0.366,0.366,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,38.0,2025-05-12,GHL_pyapp_20250512T,0.350-0.374mg/mm lrg bag blu,ES0410#2 0.372,0.372,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,39.0,2025-05-12,GHL_pyapp_20250512T,0.350-0.374mg/mm lrg bag blu,ES0415#30 0.359,0.359,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,40.0,2025-05-12,GHL_pyapp_20250512T,0.350-0.374mg/mm lrg bag blu,ES0415#27 0.354,0.354,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,41.0,2025-05-12,GHL_pyapp_20250512T,0.350-0.374mg/mm lrg bag blu,ES0415#26 0.374,0.374,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,42.0,2025-05-12,GHL_pyapp_20250512T,0.350-0.374mg/mm lrg bag blu,ES0415#22 0.366,0.366,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#%% Filter The Tests To Process
# dfmasks = [
#     (dftests['Test date']<'2025-03-28') & (dftests['Test date']>='2025-03-26'),
#     dftests['Test name'] != 'GHL_pyapp_20250326T1258'
# ]
# dfmasks = [
#     (dftests['Test date']<='2025-04-15') & (dftests['Test date']>='2025-04-14')
# ]
# dfmasks = [
#     dftests['Test date']=='2025-05-05',
# ]
dfmasks = [
    dftests['Test date']=='2025-05-12',
    dftests['Test name']!='GHL_pyapp_20250512T'
]

dffilt = dftests[np.all(dfmasks,axis=0)]
dffilt

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Unnamed: 24
38,33.0,2025-05-12,GHL_pyapp_20250512T0947,0.350-0.374mg/mm lrg bag blu,ES0414#7 0.367,0.367,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,34.0,2025-05-12,GHL_pyapp_20250512T0951,0.350-0.374mg/mm lrg bag blu,ES0414#5 0.352,0.352,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,35.0,2025-05-12,GHL_pyapp_20250512T0955,0.350-0.374mg/mm lrg bag blu,ES0415#8 0.351,0.351,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,36.0,2025-05-12,GHL_pyapp_20250512T0959,0.350-0.374mg/mm lrg bag blu,ES0408#16 0.372,0.372,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,37.0,2025-05-12,GHL_pyapp_20250512T1002,0.350-0.374mg/mm lrg bag blu,ES0409#7 0.366,0.366,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#%% Load OCT study information
octstudies = [];
folder_octexport_root = Path(r'\\file.corp.ghlabs.org\Shared\Projects\NAATOS\V1\NAATOS_OCT_WORK\OCTExport')
#folder_octexport_root = Path(r'D:\SGProjects\NAATOS\OCTlocal')

# Load list of data
for idx,record in dffilt.iterrows():
    octstudy = naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder(record['Test name'],folder_octexport_root);
    octstudies.append(octstudy);

STUDY: GHL_pyapp_20250512T0947
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T0951
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T0955
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T0959
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250512T1002
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}

In [7]:
# Master Parameters
oct_scalar_min = 30;
oct_scalar_max = 60;

In [8]:
#%% Load OCTSTUDY object, and start some processing on it
for idx,octstudy in enumerate(octstudies):
    octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder;
    print(octstudy)

    fname_merged_and_rescaled_volume = octstudy.folder_study_processed/'{:s}_STACKED_RESCALED_{:}to{:}_uint8.vtk'.format(octstudy.name,oct_scalar_min,oct_scalar_max);
    
    if(octstudy.study_info['study_num_oct_files']>0):
        # --Loading And Pre-Processing--
        if(fname_merged_and_rescaled_volume.exists()):
            pass;
            #print(f'Loading {fname_merged_and_rescaled_volume.name}')
            # Load the strip and merge into one volume
            #vdvol = vedo.Volume(pv.read(fname_merged_and_rescaled_volume));
            #octstudy.vdvol = vdvol;
        else:
            # Load OCT Data for this study
            octstudy.load_all_octs();


            # THESE WILL DO NOTHING IF ANTICIPATED OUTPUTS/ARTIFACTS ALREADY EXIST IN THE PROCESSED FOLDER

            # RGB Camera Images - Write them out as .jpg to processed folder
            naatos_oct_tools.oct_linear_scan_processing.process_rgbcamera_and_make_individual_images(octstudy);

            # RGB Camera Images - Make a montage and write out as .jpg to processed folder
            naatos_oct_tools.oct_linear_scan_processing.process_rgbcamera_and_make_montage_image(octstudy);
            #break;


            # IF MERGED STACKED AND RESCALED TO SCALAR RANGE FILE EXISTS, LOAD THAT; OTHERWISE PROCESS IT HERE
            octstudy.folder_study_processed.mkdir(exist_ok=True);
            fname = fname_merged_and_rescaled_volume;
            if(fname.exists()):
                print('Stacked volume byte-size .vtk file already exists, will not recreate.');
                print(fname);
            else:
                print(f'Generating merged and rescaled .vtk volume');
                # Generate merged and rescaled volume
                vdvol = octstudy.generate_merged_vdvol_and_rescaled(oct_scalar_min,oct_scalar_max);
                octstudy.vdvol = vdvol;
            
                # save this byte-adjusted volume
                vdvol.dataset.save(fname);
            
            # Unload OCT Data for this study (we will still keep the vdvol)
            octstudy.unload_all_octdata();

        # --Detailed Image Processing--
        if hasattr(octstudy,'vdvol'):
            del octstudy.vdvol;

<OCT_Study_Folder Object>
GHL_pyapp_20250512T0947 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
GHL_pyapp_20250512T0947_videocamera_0000 20250512T094740
GHL_pyapp_20250512T0947_videocamera_0001 20250512T094747
GHL_pyapp_20250512T0947_videocamera_0002 20250512T094754
GHL_pyapp_20250512T0947_videocamera_0003 20250512T094802
GHL_pyapp_20250512T0947_videocamera_0004 20250512T094809
GHL_pyapp_20250512T0947_videocamera_0005 20250512T094816
GHL_pyapp_20250512T0947_videocamera_0006 20250512T094824
GHL_pyapp_20250512T0947_videocamera_0007 20250512T094831
GHL_pyapp_20250512T0947_videocamera_0008 20250512T094839
GHL_pyapp_20250512T0947_videocamera_0009 20250512T094846
GHL_pyapp_20250512T0947_videocamera_0010 20250512T094853
GHL_pyapp_20250512T0947_videocamera_0011 20250512T094901
GHL_pyapp_20250512T0947_videocamera_0012 20250512T094908
GHL_pyapp_20250512T0947_videocamera_0013 20250512T094915
GHL_pyapp_20250512T0947_videocamera_0014 20250512T094923
GHL_pyapp_20250512T0947_videocamera_0015 20250512T094930
GHL_pyapp_20250512T0947_videocamera_0016 20250512T094937
GHL_pyapp_20250512T0947_videocamera_0017 20250512T094945
GHL_pyapp_20250512T0947_videocamera_0018 20250512T094952
millimeters Per Pixel X:48.33446705 Y:48.66782401
OCT Scan Center Was @ [mm]: 0.0 0.1
OCT Scan FOV    Was @ [mm]: 9.0 3.5
Video Camera Scan Pixel Width  [px]: 435.01020345
Video Camera Scan Pixel Height [px]: 170.33738403499999
Video Camera Scan Pixel Center X [px]: 0.0
Video Camera Scan Pixel Center Y [px]: 4.866782401
 SliceX  : slice(106.494898275, 541.505101725, None)
 SliceY  : slice(152.8313079825, 323.1686920175, None)
SliceXint: slice(106, 541, None)
SliceYint: slice(152, 323, None)
Generating merged and rescaled .vtk volume
SingleFOV --> Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Combined --> Image Dims:(690, 8550, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
<OCT_Study_Folder Object>
GHL_pyapp_20250512T0951 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
GHL_pyapp_20250512T0951_videocamera_0000 20250512T095146
GHL_pyapp_20250512T0951_videocamera_0001 20250512T095153
GHL_pyapp_20250512T0951_videocamera_0002 20250512T095200
GHL_pyapp_20250512T0951_videocamera_0003 20250512T095208
GHL_pyapp_20250512T0951_videocamera_0004 20250512T095215
GHL_pyapp_20250512T0951_videocamera_0005 20250512T095222
GHL_pyapp_20250512T0951_videocamera_0006 20250512T095230
GHL_pyapp_20250512T0951_videocamera_0007 20250512T095237
GHL_pyapp_20250512T0951_videocamera_0008 20250512T095245
GHL_pyapp_20250512T0951_videocamera_0009 20250512T095252
GHL_pyapp_20250512T0951_videocamera_0010 20250512T095259
GHL_pyapp_20250512T0951_videocamera_0011 20250512T095307
GHL_pyapp_20250512T0951_videocamera_0012 20250512T095314
GHL_pyapp_20250512T0951_videocamera_0013 20250512T095322
GHL_pyapp_20250512T0951_videocamera_0014 20250512T095329
GHL_pyapp_20250512T0951_videocamera_0015 20250512T095336
GHL_pyapp_20250512T0951_videocamera_0016 20250512T095344
GHL_pyapp_20250512T0951_videocamera_0017 20250512T095351
GHL_pyapp_20250512T0951_videocamera_0018 20250512T095359
millimeters Per Pixel X:48.33446705 Y:48.66782401
OCT Scan Center Was @ [mm]: 0.0 0.1
OCT Scan FOV    Was @ [mm]: 9.0 3.5
Video Camera Scan Pixel Width  [px]: 435.01020345
Video Camera Scan Pixel Height [px]: 170.33738403499999
Video Camera Scan Pixel Center X [px]: 0.0
Video Camera Scan Pixel Center Y [px]: 4.866782401
 SliceX  : slice(106.494898275, 541.505101725, None)
 SliceY  : slice(152.8313079825, 323.1686920175, None)
SliceXint: slice(106, 541, None)
SliceYint: slice(152, 323, None)
Generating merged and rescaled .vtk volume
SingleFOV --> Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Combined --> Image Dims:(690, 8550, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
<OCT_Study_Folder Object>
GHL_pyapp_20250512T0955 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
GHL_pyapp_20250512T0955_videocamera_0000 20250512T095516
GHL_pyapp_20250512T0955_videocamera_0001 20250512T095524
GHL_pyapp_20250512T0955_videocamera_0002 20250512T095531
GHL_pyapp_20250512T0955_videocamera_0003 20250512T095538
GHL_pyapp_20250512T0955_videocamera_0004 20250512T095546
GHL_pyapp_20250512T0955_videocamera_0005 20250512T095553
GHL_pyapp_20250512T0955_videocamera_0006 20250512T095601
GHL_pyapp_20250512T0955_videocamera_0007 20250512T095608
GHL_pyapp_20250512T0955_videocamera_0008 20250512T095615
GHL_pyapp_20250512T0955_videocamera_0009 20250512T095623
GHL_pyapp_20250512T0955_videocamera_0010 20250512T095630
GHL_pyapp_20250512T0955_videocamera_0011 20250512T095638
GHL_pyapp_20250512T0955_videocamera_0012 20250512T095645
GHL_pyapp_20250512T0955_videocamera_0013 20250512T095652
GHL_pyapp_20250512T0955_videocamera_0014 20250512T095700
GHL_pyapp_20250512T0955_videocamera_0015 20250512T095707
GHL_pyapp_20250512T0955_videocamera_0016 20250512T095715
GHL_pyapp_20250512T0955_videocamera_0017 20250512T095722
GHL_pyapp_20250512T0955_videocamera_0018 20250512T095729
millimeters Per Pixel X:48.33446705 Y:48.66782401
OCT Scan Center Was @ [mm]: 0.0 0.1
OCT Scan FOV    Was @ [mm]: 9.0 3.5
Video Camera Scan Pixel Width  [px]: 435.01020345
Video Camera Scan Pixel Height [px]: 170.33738403499999
Video Camera Scan Pixel Center X [px]: 0.0
Video Camera Scan Pixel Center Y [px]: 4.866782401
 SliceX  : slice(106.494898275, 541.505101725, None)
 SliceY  : slice(152.8313079825, 323.1686920175, None)
SliceXint: slice(106, 541, None)
SliceYint: slice(152, 323, None)
Generating merged and rescaled .vtk volume
SingleFOV --> Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Combined --> Image Dims:(690, 8550, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
<OCT_Study_Folder Object>
GHL_pyapp_20250512T0959 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
GHL_pyapp_20250512T0959_videocamera_0000 20250512T095937
GHL_pyapp_20250512T0959_videocamera_0001 20250512T095945
GHL_pyapp_20250512T0959_videocamera_0002 20250512T095952
GHL_pyapp_20250512T0959_videocamera_0003 20250512T100000
GHL_pyapp_20250512T0959_videocamera_0004 20250512T100007
GHL_pyapp_20250512T0959_videocamera_0005 20250512T100015
GHL_pyapp_20250512T0959_videocamera_0006 20250512T100022
GHL_pyapp_20250512T0959_videocamera_0007 20250512T100029
GHL_pyapp_20250512T0959_videocamera_0008 20250512T100037
GHL_pyapp_20250512T0959_videocamera_0009 20250512T100044
GHL_pyapp_20250512T0959_videocamera_0010 20250512T100052
GHL_pyapp_20250512T0959_videocamera_0011 20250512T100059
GHL_pyapp_20250512T0959_videocamera_0012 20250512T100107
GHL_pyapp_20250512T0959_videocamera_0013 20250512T100114
GHL_pyapp_20250512T0959_videocamera_0014 20250512T100121
GHL_pyapp_20250512T0959_videocamera_0015 20250512T100129
GHL_pyapp_20250512T0959_videocamera_0016 20250512T100136
GHL_pyapp_20250512T0959_videocamera_0017 20250512T100144
GHL_pyapp_20250512T0959_videocamera_0018 20250512T100151
millimeters Per Pixel X:48.33446705 Y:48.66782401
OCT Scan Center Was @ [mm]: 0.0 0.1
OCT Scan FOV    Was @ [mm]: 9.0 3.5
Video Camera Scan Pixel Width  [px]: 435.01020345
Video Camera Scan Pixel Height [px]: 170.33738403499999
Video Camera Scan Pixel Center X [px]: 0.0
Video Camera Scan Pixel Center Y [px]: 4.866782401
 SliceX  : slice(106.494898275, 541.505101725, None)
 SliceY  : slice(152.8313079825, 323.1686920175, None)
SliceXint: slice(106, 541, None)
SliceYint: slice(152, 323, None)
Generating merged and rescaled .vtk volume
SingleFOV --> Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Combined --> Image Dims:(690, 8550, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
<OCT_Study_Folder Object>
GHL_pyapp_20250512T1002 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
GHL_pyapp_20250512T1002_videocamera_0000 20250512T100307
GHL_pyapp_20250512T1002_videocamera_0001 20250512T100314
GHL_pyapp_20250512T1002_videocamera_0002 20250512T100321
GHL_pyapp_20250512T1002_videocamera_0003 20250512T100329
GHL_pyapp_20250512T1002_videocamera_0004 20250512T100336
GHL_pyapp_20250512T1002_videocamera_0005 20250512T100344
GHL_pyapp_20250512T1002_videocamera_0006 20250512T100351
GHL_pyapp_20250512T1002_videocamera_0007 20250512T100358
GHL_pyapp_20250512T1002_videocamera_0008 20250512T100406
GHL_pyapp_20250512T1002_videocamera_0009 20250512T100413
GHL_pyapp_20250512T1002_videocamera_0010 20250512T100421
GHL_pyapp_20250512T1002_videocamera_0011 20250512T100428
GHL_pyapp_20250512T1002_videocamera_0012 20250512T100436
GHL_pyapp_20250512T1002_videocamera_0013 20250512T100443
GHL_pyapp_20250512T1002_videocamera_0014 20250512T100451
GHL_pyapp_20250512T1002_videocamera_0015 20250512T100458
GHL_pyapp_20250512T1002_videocamera_0016 20250512T100506
GHL_pyapp_20250512T1002_videocamera_0017 20250512T100513
GHL_pyapp_20250512T1002_videocamera_0018 20250512T100521
millimeters Per Pixel X:48.33446705 Y:48.66782401
OCT Scan Center Was @ [mm]: 0.0 0.1
OCT Scan FOV    Was @ [mm]: 9.0 3.5
Video Camera Scan Pixel Width  [px]: 435.01020345
Video Camera Scan Pixel Height [px]: 170.33738403499999
Video Camera Scan Pixel Center X [px]: 0.0
Video Camera Scan Pixel Center Y [px]: 4.866782401
 SliceX  : slice(106.494898275, 541.505101725, None)
 SliceY  : slice(152.8313079825, 323.1686920175, None)
SliceXint: slice(106, 541, None)
SliceYint: slice(152, 323, None)
Generating merged and rescaled .vtk volume
SingleFOV --> Image Dims:(690, 450, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)
Combined --> Image Dims:(690, 8550, 175) PixelSpacing[mm]:(0.003475, 0.02, 0.02)

# (util) delete some items from processed folder

In [ ]:
if False:
    for idx,octstudy in enumerate(octstudies):
        print('~~~~~~~');
        print(octstudy.name);
        fname = (octstudy.folder_study_processed/'along_strip_data_extracted.hdf5')
        if(fname.exists()):
            print('deleted',fname.name);
            fname.unlink();

# Call Notebooks - Processing A to D and E

In [9]:
#%% Load OCTSTUDY object, and start some processing on it
octstudies_to_run = [];
norunlist = [
    #'GHL_pyapp_20250508T1112','GHL_pyapp_20250508T1128','GHL_pyapp_20250508T1134','GHL_pyapp_20250508T1143'
]
forcerunlist = [
    #'GHL_pyapp_20250508T1151',
    #'GHL_pyapp_20250508T1601',
    #'GHL_pyapp_20250508T1608',
]
for idx,octstudy in enumerate(octstudies):
    octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder;
    print('~~~~~~~');
    print(octstudy.name);
    rescheck = octstudy.resultsCheck();
    pp.pprint(rescheck)
    doWeRunTheNotebook = any([v is False for k,v in rescheck.items()])
    doWeRunTheNotebook = doWeRunTheNotebook or ('/dfstepE' not in rescheck['along_strip_data_extracted']);
    print('Run?',doWeRunTheNotebook)
    if((doWeRunTheNotebook and octstudy.name not in norunlist) or (octstudy.name in forcerunlist)):
        octstudies_to_run.append(octstudy);
    # if(octstudy.name in forcerunlist):
    #     octstudies_to_run.append(octstudy);

# if(len(octstudies_to_run)>4):
#     #octstudies_to_run=octstudies_to_run[0:4];
#     #octstudies_to_run=octstudies_to_run[-4:];
#     print('only a subset');
#     norunlist = [
#         'GHL_pyapp_20250508T1112','GHL_pyapp_20250508T1128','GHL_pyapp_20250508T1134','GHL_pyapp_20250508T1143'
#     ]
#     octstudies_to_run = [s for s in octstudies_to_run if s.name not in norunlist ]
#     pass;

print('~~~~~~~');
print('We will run the processing on {:} octstudies.'.format(len(octstudies_to_run)))
print([x.name for x in octstudies_to_run])

~~~~~~~
GHL_pyapp_20250512T0947
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250512T0951
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250512T0955
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250512T0959
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250512T1002
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
We will run the processing on 5 octstudies.
['GHL_pyapp_20250512T0947', 'GHL_pyapp_20250512T0951', 'GHL_pyapp_20250512T0955', 'GHL_pyapp_20250512T0959', 'GHL_pyapp_20250512T1002']

In [ ]:
#nbpath_out = Path(r'D:\TEMP\OCTtmp')/(Path(nbpath).stem+'_OUT{:s}.ipynb').format(octstudy.name)
#nbpath_out.parent

# Prepare notebooks we will call

In [10]:
#nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\nb_test_nbparams.ipynb";
#nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250429_process_a_longstrip.ipynb";
nbpaths = [
    r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250509_process_a_longstrip.ipynb",
    r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250507_process_E_longstripmetric.ipynb"
];
for nbpath in nbpaths:
    print('Notebook:',Path(nbpath).name);
    parameters = papermill.inspect_notebook(nbpath)
    pp.pprint(parameters.keys());

Notebook: octproc_20250509_process_a_longstrip.ipynb
dict_keys(['oct_scalar_min', 'oct_scalar_max', 'codename', 'study_name', 'folder_octexport_root', 'folder_figure_temp'])
Notebook: octproc_20250507_process_E_longstripmetric.ipynb
dict_keys(['oct_scalar_min', 'oct_scalar_max', 'codename', 'folder_octexport_root', 'study_name', 'folder_figure_temp'])

# Call notebooks to process (Multiple-strips in parallel, concurrent futures)

In [11]:
import concurrent.futures

def run_notebook_on_an_octstudy(octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder):

    folder_temp_path = Path(r'D:\TEMP\OCTtmp');
    folder_temp_path.mkdir(parents=True,exist_ok=True);

    # run each notebook we have defined to be run
    nnotebooks = len(nbpaths);
    for count,nbpath in enumerate(nbpaths):
        nbpath = Path(nbpath)
        nbpath_out = folder_temp_path/(nbpath.stem+'_OUT_{:s}.ipynb').format(octstudy.name)

        # execute a notebook
        print(f'Launching for {octstudy.name} the {count+1}/{nnotebooks} notebook {nbpath.name} ...')
        try:
            papermill.execute_notebook(
                input_path=nbpath,
                output_path=nbpath_out,
                parameters=dict(
                    folder_octexport_root=folder_octexport_root.as_posix(),
                    codename = Path(nbpath).name,
                    study_name=octstudy.name,
                    folder_figure_temp=nbpath_out.parent.as_posix()
                )
            )
            print(f'Finished for {octstudy.name} the {count+1}/{nnotebooks} notebook {nbpath.name} !')
        except Exception as e:
            print(f'FAILED for {octstudy.name} the {count+1}/{nnotebooks} notebook {nbpath.name} !')
            break;
    print(f'alldone for {octstudy.name}')


# Using concurrent.futures to handle multiprocessing
def run_in_parallel(num_processes):
    # with concurrent.futures.ProcessPoolExecutor(max_workers=num_processes) as executor:
    #     futures = [executor.submit(run_notebook_on_an_octstudy, octstudy) for octstudy in octstudies_to_run]
    #     for future in concurrent.futures.as_completed(futures):
    #         print(future.result())  # You can handle results or exceptions here
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_processes) as executor:
        futures = [executor.submit(run_notebook_on_an_octstudy, octstudy) for octstudy in octstudies_to_run]
        for future in concurrent.futures.as_completed(futures):
            print(future.result());

# Example usage
num_processes = 10;  # Number of parallel processes
run_in_parallel(num_processes);

Launching for GHL_pyapp_20250512T0947 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250512T0951 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250512T0955 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250512T0959 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250512T1002 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/54 [00:00<?, ?cell/s]

Executing:   0%|          | 0/54 [00:00<?, ?cell/s]

Executing:   0%|          | 0/54 [00:00<?, ?cell/s]

Executing:   0%|          | 0/54 [00:00<?, ?cell/s]

Executing:   0%|          | 0/54 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250512T0955 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250512T0955 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250512T0959 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250512T0959 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250512T1002 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250512T1002 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250512T0955 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250512T0955
None
Finished for GHL_pyapp_20250512T0959 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250512T0959
None
Finished for GHL_pyapp_20250512T1002 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250512T1002
None
Finished for GHL_pyapp_20250512T0947 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250512T0947 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250512T0951 the 1/2 notebook octproc_20250509_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250512T0951 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250512T0947 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250512T0947
None
Finished for GHL_pyapp_20250512T0951 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250512T0951
None

In [ ]:
import concurrent.futures
import time

def task(n):
    time.sleep(1)
    return n * n

# Using ThreadPoolExecutor
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
    futures = [executor.submit(task, i) for i in range(10)]
    for future in concurrent.futures.as_completed(futures):
        print(future.result())

# # Using ProcessPoolExecutor
# with concurrent.futures.ProcessPoolExecutor(max_workers=5) as executor:
#     results = executor.map(task, range(10))
#     for result in results:
#         print(result)

# Call Notebooks - Processing E

In [ ]:
#%% Load OCTSTUDY object, and start some processing on it
octstudies_to_run = [];
for idx,octstudy in enumerate(octstudies):
    octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder;
    print('~~~~~~~');
    print(octstudy.name);
    rescheck = octstudy.resultsCheck();
    pp.pprint(rescheck);
    doWeRunTheNotebook = not any([v is False for k,v in rescheck.items()])
    doWeRunTheNotebook = doWeRunTheNotebook and ('/dfstepE' in rescheck['along_strip_data_extracted']);
    print('Run?',not doWeRunTheNotebook)
    if(not doWeRunTheNotebook):
        octstudies_to_run.append(octstudy);

print('~~~~~~~');
print('We will run the processing on {:} octstudies.'.format(len(octstudies_to_run)))
print([x.name for x in octstudies_to_run])

In [ ]:
# Prepare notebook to run
import papermill

#nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\nb_test_nbparams.ipynb";
#nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250429_process_a_longstrip.ipynb";
nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250507_process_E_longstripmetric.ipynb";

parameters = papermill.inspect_notebook(nbpath)
pp.pprint(parameters);

In [ ]:
# Call notebooks in parallel
import concurrent.futures

def run_notebook_on_an_octstudy(octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder):
    folder_temp_path = Path(r'D:\TEMP\OCTtmp');

    for nbpath in nbpaths:
        nbpath_out = folder_temp_path/(Path(nbpath).stem+'_OUT_{:s}.ipynb').format(octstudy.name)

    # set output path
    #nbpath_out = Path(nbpath).parent/(Path(nbpath).stem+'_OUT{:s}.ipynb').format(octstudy.name)
    nbpath_out = Path(r'C:\TEMP\OCTtmp')/(Path(nbpath).stem+'_OUT_{:s}.ipynb').format(octstudy.name)
    print(nbpath_out);

    # # execute a notebook
    papermill.execute_notebook(
        input_path=nbpath,
        output_path=nbpath_out,
        parameters=dict(codename = Path(nbpath).name,study_name=octstudy.name)
    )
    # print('start',octstudy.name);
    # time.sleep(1)
    # print('stop',octstudy.name)

# Using concurrent.futures to handle multiprocessing
def run_in_parallel(num_processes):
    # with concurrent.futures.ProcessPoolExecutor(max_workers=num_processes) as executor:
    #     futures = [executor.submit(run_notebook_on_an_octstudy, octstudy) for octstudy in octstudies_to_run]
    #     for future in concurrent.futures.as_completed(futures):
    #         print(future.result())  # You can handle results or exceptions here
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_processes) as executor:
        futures = [executor.submit(run_notebook_on_an_octstudy, octstudy) for octstudy in octstudies_to_run]
        for future in concurrent.futures.as_completed(futures):
            print(future.result())

# Example usage
num_processes = 4;  # Number of parallel processes
run_in_parallel(num_processes);

# Processing Step 0 - Replace VTK scalars with scaled bytes

In [ ]:
#del vdvol;
#del scalars_rescaled_as_int

# Develop VTK Range Rescaling and integer

In [ ]:
def doVtkImageMinMaxScaling(vtkimagedata):
    # restrict range and re-scale, cast to integer (will reduce memory by 4x)
    oct_scalar_min = 30;
    oct_scalar_max = 60;

    import vtk

    # Create VTK Pipeline Connections
    # 1. Thresholding Hi
    alg_thresholder = vtk.vtkImageThreshold();
    alg_thresholder.SetInputData(vtkimagedata)
    alg_thresholder.ThresholdByUpper(oct_scalar_min);
    alg_thresholder.SetOutValue(oct_scalar_min);
    alg_thresholder.ReplaceInOff();
    alg_thresholder.ReplaceOutOn();

    # 2. Thresholding Lo
    alg_thresholder2 = vtk.vtkImageThreshold();
    alg_thresholder2.SetInputConnection(alg_thresholder.GetOutputPort());
    alg_thresholder2.ThresholdByLower(oct_scalar_max);
    alg_thresholder2.SetOutValue(oct_scalar_max);
    alg_thresholder2.ReplaceInOff();
    alg_thresholder2.ReplaceOutOn();

    # 3. Subtract Minimum Value
    alg_math1 = vtk.vtkImageMathematics();
    alg_math1.SetInputConnection(alg_thresholder2.GetOutputPort());
    alg_math1.SetConstantC(-oct_scalar_min);
    alg_math1.SetOperationToAddConstant();

    # 4. Rescale to 0 to 255
    alg_math2 = vtk.vtkImageMathematics();
    alg_math2.SetInputConnection(alg_math1.GetOutputPort());
    alg_math2.SetConstantK(255.0/oct_scalar_min);
    alg_math2.SetOperationToMultiplyByK();
    #cast to unit8_t byte
    #alg_math2.SetOutputS();

    # 5. Cast to Uint8
    alg_caster = vtk.vtkImageCast();
    alg_caster.SetInputConnection(alg_math2.GetOutputPort());
    alg_caster.SetOutputScalarTypeToUnsignedChar();


    # execute the vtk pipline, wrap with pyvista, and return
    alg_final = alg_caster;
    alg_final.Update();

    final = pv.wrap(alg_final.GetOutput())
    return final;
mergedvol_rescaled = doVtkImageMinMaxScaling(mergedvol);

In [ ]:
np.max(mergedvol.active_scalars)

In [ ]:
print(np.min(mergedvol_rescaled.active_scalars),np.max(mergedvol_rescaled.active_scalars))

In [ ]:
mergedvol_rescaled['OCTintensity']

In [ ]:
del mergedvol,mergedvol_rescaled,alg_thresholder

In [ ]:
del alg_final